import type { AuthUser } from "@/lib/api-client";
import { DEFAULT_ROLE_PERMISSIONS } from "@/lib/rbac";

/**
 * RBAC system roles + employee identity keys.
 */
export type DemoRoleKey =
  | "Admin"
  | "CEO"
  | "COO"
  | "CTO"
  | "IT Admin"
  | "Accounts"
  | "HR"
  | "Sales Manager"
  | "Sales team member"
  | "PMO"
  | "EngagementManager"
  | "Intern"
  | "Testing HOD"
  | "Testing Senior Manager"
  | "Testing-Manager"
  | "Testing-Team Leader"
  | "Testing-Team Member"
  | "Consulting-HOD"
  | "Consulting-Senior Manager"
  | "Consulting-Manager"
  | "Consulting-Team Leader"
  | "Consulting-Team member"
  | "SOC-HOD"
  | "SOC-Senior Manager"
  | "SOC-Manager"
  | "SOC-Team Leader"
  | "SOC-Team Member"
  | "R&D - Team member"
  | (string & {});

export const DEMO_ROLE_STORAGE_KEY = "pulse-demo-role";

export interface DemoPersona {
  key: string;
  code: string;
  label: string;
  category: string;
  email: string;
  name: string;
  id: string;
  avatar: string;
  department: string;
  designation: string;
  roleKey: string;
  permissions: string[];
}

export const DEMO_PERSONAS: DemoPersona[] = [
  {
    key: "TK-0001",
    code: "TK-0001",
    label: "Director and Chief Executive Officer",
    category: "Core",
    email: "vikrant@acme.co",
    name: "Vikrant Malhotra",
    id: "00000000-0000-4000-8000-000000000001",
    avatar: "VM",
    department: "Core",
    designation: "Director and Chief Executive Officer",
    roleKey: "CEO",
    permissions: DEFAULT_ROLE_PERMISSIONS["CEO" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0002",
    code: "TK-0002",
    label: "Director and Chief Operating Officer",
    category: "Core",
    email: "dhanshree@acme.co",
    name: "Dhanshree Pansare",
    id: "00000000-0000-4000-8000-000000000002",
    avatar: "DP",
    department: "Core",
    designation: "Director and Chief Operating Officer",
    roleKey: "COO",
    permissions: DEFAULT_ROLE_PERMISSIONS["COO" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0003",
    code: "TK-0003",
    label: "Director and Chief Technology Officer",
    category: "Core",
    email: "kunal.deshmukh@acme.co",
    name: "Kunal Deshmukh",
    id: "00000000-0000-4000-8000-000000000003",
    avatar: "KD",
    department: "Core",
    designation: "Director and Chief Technology Officer",
    roleKey: "CTO",
    permissions: DEFAULT_ROLE_PERMISSIONS["CTO" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0004",
    code: "TK-0004",
    label: "System Administrator",
    category: "Core",
    email: "admin@acme.co",
    name: "Admin User",
    id: "00000000-0000-4000-8000-000000000004",
    avatar: "AU",
    department: "Core",
    designation: "System Administrator",
    roleKey: "Admin",
    permissions: DEFAULT_ROLE_PERMISSIONS["Admin"] ?? [],
  },
  {
    key: "TK-0004-IT",
    code: "TK-0004-IT",
    label: "IT Administrator",
    category: "Functional - IT Administration",
    email: "itadmin@acme.co",
    name: "IT Admin User",
    id: "a0000000-0000-0000-0000-000000000032",
    avatar: "IT",
    department: "Functional - IT Administration",
    designation: "IT Administrator",
    roleKey: "IT Admin",
    permissions: DEFAULT_ROLE_PERMISSIONS["IT Admin"] ?? [],
  },
  {
    key: "TK-0005",
    code: "TK-0005",
    label: "Senior Accountant - I",
    category: "Functional - Accounts",
    email: "accounts@acme.co",
    name: "Accounts User",
    id: "00000000-0000-4000-8000-000000000005",
    avatar: "AU",
    department: "Functional - Accounts",
    designation: "Senior Accountant - I",
    roleKey: "Accounts",
    permissions: DEFAULT_ROLE_PERMISSIONS["Accounts" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0006",
    code: "TK-0006",
    label: "HR Head",
    category: "Functional - HR",
    email: "hr@acme.co",
    name: "HR User",
    id: "00000000-0000-4000-8000-000000000006",
    avatar: "HU",
    department: "Functional - HR",
    designation: "HR Head",
    roleKey: "HR",
    permissions: DEFAULT_ROLE_PERMISSIONS["HR" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0007",
    code: "TK-0007",
    label: "Sales Manager",
    category: "Functional - Sales",
    email: "sales@acme.co",
    name: "Sales User",
    id: "00000000-0000-4000-8000-000000000007",
    avatar: "SU",
    department: "Functional - Sales",
    designation: "Sales Manager",
    roleKey: "Sales Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["Sales Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0008",
    code: "TK-0008",
    label: "Sales Associate",
    category: "Functional - Sales",
    email: "nikhil.khanna@acme.co",
    name: "Nikhil Khanna",
    id: "00000000-0000-4000-8000-000000000008",
    avatar: "NK",
    department: "Functional - Sales",
    designation: "Sales Associate",
    roleKey: "Sales team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Sales team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0009",
    code: "TK-0009",
    label: "Sales Associate",
    category: "Functional - Sales",
    email: "pooja.sharma@acme.co",
    name: "Pooja Sharma",
    id: "00000000-0000-4000-8000-000000000009",
    avatar: "PS",
    department: "Functional - Sales",
    designation: "Sales Associate",
    roleKey: "Sales team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Sales team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0010",
    code: "TK-0010",
    label: "Associate Customer Success Representative - I",
    category: "Functional - Sales",
    email: "rohit.verma@acme.co",
    name: "Rohit Verma",
    id: "00000000-0000-4000-8000-000000000010",
    avatar: "RV",
    department: "Functional - Sales",
    designation: "Associate Customer Success Representative - I",
    roleKey: "Sales team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Sales team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0011",
    code: "TK-0011",
    label: "Associate Customer Success Representative - II",
    category: "Functional - Sales",
    email: "sneha.reddy@acme.co",
    name: "Sneha Reddy",
    id: "00000000-0000-4000-8000-000000000011",
    avatar: "SR",
    department: "Functional - Sales",
    designation: "Associate Customer Success Representative - II",
    roleKey: "Sales team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Sales team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0012",
    code: "TK-0012",
    label: "Senior PMO - I",
    category: "Functional - Project Management",
    email: "rahul@acme.co",
    name: "Rahul Gupta",
    id: "00000000-0000-4000-8000-000000000012",
    avatar: "RG",
    department: "Functional - Project Management",
    designation: "Senior PMO - I",
    roleKey: "PMO",
    permissions: DEFAULT_ROLE_PERMISSIONS["PMO" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0013",
    code: "TK-0013",
    label: "Engagement Manager",
    category: "Functional - Project Management",
    email: "riya@acme.co",
    name: "Riya Kapoor",
    id: "00000000-0000-4000-8000-000000000013",
    avatar: "RK",
    department: "Functional - Project Management",
    designation: "Engagement Manager",
    roleKey: "EngagementManager",
    permissions: DEFAULT_ROLE_PERMISSIONS["EngagementManager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0014",
    code: "TK-0014",
    label: "Engagement Manager",
    category: "Functional - Project Management",
    email: "pradeep.singh@acme.co",
    name: "Pradeep Singh",
    id: "00000000-0000-4000-8000-000000000014",
    avatar: "PS",
    department: "Functional - Project Management",
    designation: "Engagement Manager",
    roleKey: "EngagementManager",
    permissions: DEFAULT_ROLE_PERMISSIONS["EngagementManager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0015",
    code: "TK-0015",
    label: "Python Developer - II",
    category: "R&D (Research & Development)",
    email: "kavya.desai@acme.co",
    name: "Kavya Desai",
    id: "00000000-0000-4000-8000-000000000015",
    avatar: "KD",
    department: "R&D (Research & Development)",
    designation: "Python Developer - II",
    roleKey: "R&D - Team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["R&D - Team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0016",
    code: "TK-0016",
    label: "SOC HOD",
    category: "Services - Operations",
    email: "rajesh.kadam@acme.co",
    name: "Rajesh Kadam",
    id: "00000000-0000-4000-8000-000000000016",
    avatar: "RK",
    department: "Services - Operations",
    designation: "SOC HOD",
    roleKey: "SOC-HOD",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-HOD" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0017",
    code: "TK-0017",
    label: "SOC Senior Manager",
    category: "Services - Operations",
    email: "deepak.sawant@acme.co",
    name: "Deepak Sawant",
    id: "00000000-0000-4000-8000-000000000017",
    avatar: "DS",
    department: "Services - Operations",
    designation: "SOC Senior Manager",
    roleKey: "SOC-Senior Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Senior Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0018",
    code: "TK-0018",
    label: "SOC Manager",
    category: "Services - Operations",
    email: "vikram@acme.co",
    name: "Vikram Shah",
    id: "00000000-0000-4000-8000-000000000018",
    avatar: "VS",
    department: "Services - Operations",
    designation: "SOC Manager",
    roleKey: "SOC-Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0019",
    code: "TK-0019",
    label: "SOC Lead - I",
    category: "Services - Operations",
    email: "sneha.iyer@acme.co",
    name: "Sneha Iyer",
    id: "00000000-0000-4000-8000-000000000019",
    avatar: "SI",
    department: "Services - Operations",
    designation: "SOC Lead - I",
    roleKey: "SOC-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0020",
    code: "TK-0020",
    label: "SOC Lead - II",
    category: "Services - Operations",
    email: "nikhil@acme.co",
    name: "Nikhil Rao",
    id: "00000000-0000-4000-8000-000000000020",
    avatar: "NR",
    department: "Services - Operations",
    designation: "SOC Lead - II",
    roleKey: "SOC-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0021",
    code: "TK-0021",
    label: "SOC Shift Lead - I",
    category: "Services - Operations",
    email: "amit.pandey@acme.co",
    name: "Amit Pandey",
    id: "00000000-0000-4000-8000-000000000021",
    avatar: "AP",
    department: "Services - Operations",
    designation: "SOC Shift Lead - I",
    roleKey: "SOC-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0022",
    code: "TK-0022",
    label: "SOC Analyst - I",
    category: "Services - Operations",
    email: "karthik.bose@acme.co",
    name: "Karthik Bose",
    id: "00000000-0000-4000-8000-000000000022",
    avatar: "KB",
    department: "Services - Operations",
    designation: "SOC Analyst - I",
    roleKey: "SOC-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0023",
    code: "TK-0023",
    label: "SOC Analyst - II",
    category: "Services - Operations",
    email: "ankit.verma@acme.co",
    name: "Ankit Verma",
    id: "00000000-0000-4000-8000-000000000023",
    avatar: "AV",
    department: "Services - Operations",
    designation: "SOC Analyst - II",
    roleKey: "SOC-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0024",
    code: "TK-0024",
    label: "SIEM Admin - II",
    category: "Services - Operations",
    email: "aditya.reddy@acme.co",
    name: "Aditya Reddy",
    id: "00000000-0000-4000-8000-000000000024",
    avatar: "AR",
    department: "Services - Operations",
    designation: "SIEM Admin - II",
    roleKey: "SOC-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0025",
    code: "TK-0025",
    label: "SOC Consultant - I",
    category: "Services - Operations",
    email: "manish.tiwari@acme.co",
    name: "Manish Tiwari",
    id: "00000000-0000-4000-8000-000000000025",
    avatar: "MT",
    department: "Services - Operations",
    designation: "SOC Consultant - I",
    roleKey: "SOC-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0026",
    code: "TK-0026",
    label: "SOC Analyst - III",
    category: "Services - Operations",
    email: "pooja.nair@acme.co",
    name: "Pooja Nair",
    id: "00000000-0000-4000-8000-000000000026",
    avatar: "PN",
    department: "Services - Operations",
    designation: "SOC Analyst - III",
    roleKey: "SOC-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0027",
    code: "TK-0027",
    label: "Senior Vice President - Principal Consultant",
    category: "Services - Consulting",
    email: "anita@acme.co",
    name: "Anita Desai",
    id: "00000000-0000-4000-8000-000000000027",
    avatar: "AD",
    department: "Services - Consulting",
    designation: "Senior Vice President - Principal Consultant",
    roleKey: "Consulting-HOD",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-HOD" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0028",
    code: "TK-0028",
    label: "Principal Manager - I",
    category: "Services - Operations",
    email: "aarav@acme.co",
    name: "Aarav Mehta",
    id: "00000000-0000-4000-8000-000000000028",
    avatar: "AM",
    department: "Services - Operations",
    designation: "Principal Manager - I",
    roleKey: "SOC-Senior Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["SOC-Senior Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0029",
    code: "TK-0029",
    label: "Associate Manager - III",
    category: "Services - Consulting",
    email: "sana@acme.co",
    name: "Sana Iyer",
    id: "00000000-0000-4000-8000-000000000029",
    avatar: "SI",
    department: "Services - Consulting",
    designation: "Associate Manager - III",
    roleKey: "Consulting-Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0030",
    code: "TK-0030",
    label: "Senior GRC Auditor - I",
    category: "Services - Consulting",
    email: "priya@acme.co",
    name: "Priya Verma",
    id: "00000000-0000-4000-8000-000000000030",
    avatar: "PV",
    department: "Services - Consulting",
    designation: "Senior GRC Auditor - I",
    roleKey: "Consulting-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0031",
    code: "TK-0031",
    label: "Senior GRC Auditor - II",
    category: "Services - Consulting",
    email: "siddharth.roy@acme.co",
    name: "Siddharth Roy",
    id: "00000000-0000-4000-8000-000000000031",
    avatar: "SR",
    department: "Services - Consulting",
    designation: "Senior GRC Auditor - II",
    roleKey: "Consulting-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0032",
    code: "TK-0032",
    label: "GRC Auditor - I",
    category: "Services - Consulting",
    email: "ira.kapoor@acme.co",
    name: "Ira Kapoor",
    id: "00000000-0000-4000-8000-000000000032",
    avatar: "IK",
    department: "Services - Consulting",
    designation: "GRC Auditor - I",
    roleKey: "Consulting-Team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0033",
    code: "TK-0033",
    label: "GRC Auditor - II",
    category: "Services - Consulting",
    email: "meera.nambiar@acme.co",
    name: "Meera Nambiar",
    id: "00000000-0000-4000-8000-000000000033",
    avatar: "MN",
    department: "Services - Consulting",
    designation: "GRC Auditor - II",
    roleKey: "Consulting-Team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0034",
    code: "TK-0034",
    label: "GRC Auditor - III",
    category: "Services - Consulting",
    email: "rajat.singhal@acme.co",
    name: "Rajat Singhal",
    id: "00000000-0000-4000-8000-000000000034",
    avatar: "RS",
    department: "Services - Consulting",
    designation: "GRC Auditor - III",
    roleKey: "Consulting-Team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0035",
    code: "TK-0035",
    label: "GRC Auditor - IV",
    category: "Services - Consulting",
    email: "swati.mishra@acme.co",
    name: "Swati Mishra",
    id: "00000000-0000-4000-8000-000000000035",
    avatar: "SM",
    department: "Services - Consulting",
    designation: "GRC Auditor - IV",
    roleKey: "Consulting-Team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0036",
    code: "TK-0036",
    label: "GRC Auditor - I",
    category: "Services - Consulting",
    email: "varun.saxena@acme.co",
    name: "Varun Saxena",
    id: "00000000-0000-4000-8000-000000000036",
    avatar: "VS",
    department: "Services - Consulting",
    designation: "GRC Auditor - I",
    roleKey: "Consulting-Team member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Consulting-Team member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0037",
    code: "TK-0037",
    label: "Testing HOD",
    category: "Services - Testing",
    email: "girish.shenoy@acme.co",
    name: "Girish Shenoy",
    id: "00000000-0000-4000-8000-000000000037",
    avatar: "GS",
    department: "Services - Testing",
    designation: "Testing HOD",
    roleKey: "Testing HOD",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing HOD" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0038",
    code: "TK-0038",
    label: "Manager - I",
    category: "Services - Testing",
    email: "suresh.pillai@acme.co",
    name: "Suresh Pillai",
    id: "00000000-0000-4000-8000-000000000038",
    avatar: "SP",
    department: "Services - Testing",
    designation: "Manager - I",
    roleKey: "Testing Senior Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing Senior Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0039",
    code: "TK-0039",
    label: "Associate Manager - III",
    category: "Services - Testing",
    email: "alok.kumar@acme.co",
    name: "Alok Kumar",
    id: "00000000-0000-4000-8000-000000000039",
    avatar: "AK",
    department: "Services - Testing",
    designation: "Associate Manager - III",
    roleKey: "Testing-Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0040",
    code: "TK-0040",
    label: "Associate Project Manager",
    category: "Services - Testing",
    email: "divya.rao@acme.co",
    name: "Divya Rao",
    id: "00000000-0000-4000-8000-000000000040",
    avatar: "DR",
    department: "Services - Testing",
    designation: "Associate Project Manager",
    roleKey: "Testing-Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0041",
    code: "TK-0041",
    label: "DevSecOps Specialist - II",
    category: "Services - Testing",
    email: "manoj.bhatt@acme.co",
    name: "Manoj Bhatt",
    id: "00000000-0000-4000-8000-000000000041",
    avatar: "MB",
    department: "Services - Testing",
    designation: "DevSecOps Specialist - II",
    roleKey: "Testing-Manager",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Manager" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0042",
    code: "TK-0042",
    label: "DevSecOps Associate",
    category: "Services - Testing",
    email: "gaurav.joshi@acme.co",
    name: "Gaurav Joshi",
    id: "00000000-0000-4000-8000-000000000042",
    avatar: "GJ",
    department: "Services - Testing",
    designation: "DevSecOps Associate",
    roleKey: "Testing-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0043",
    code: "TK-0043",
    label: "Associate Manager - I",
    category: "Services - Testing",
    email: "kiran.mathur@acme.co",
    name: "Kiran Mathur",
    id: "00000000-0000-4000-8000-000000000043",
    avatar: "KM",
    department: "Services - Testing",
    designation: "Associate Manager - I",
    roleKey: "Testing-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0044",
    code: "TK-0044",
    label: "Associate Manager - II",
    category: "Services - Testing",
    email: "ramesh.nair@acme.co",
    name: "Ramesh Nair",
    id: "00000000-0000-4000-8000-000000000044",
    avatar: "RN",
    department: "Services - Testing",
    designation: "Associate Manager - II",
    roleKey: "Testing-Team Leader",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Leader" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0045",
    code: "TK-0045",
    label: "PenTester - I",
    category: "Services - Testing",
    email: "priya.sharma@acme.co",
    name: "Priya Sharma",
    id: "00000000-0000-4000-8000-000000000045",
    avatar: "PS",
    department: "Services - Testing",
    designation: "PenTester - I",
    roleKey: "Testing-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0046",
    code: "TK-0046",
    label: "PenTester - II",
    category: "Services - Testing",
    email: "arjun@acme.co",
    name: "Arjun Singh",
    id: "00000000-0000-4000-8000-000000000046",
    avatar: "AS",
    department: "Services - Testing",
    designation: "PenTester - II",
    roleKey: "Testing-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0047",
    code: "TK-0047",
    label: "DevSecOps Practitioner - I",
    category: "Services - Testing",
    email: "meera@acme.co",
    name: "Meera Joshi",
    id: "00000000-0000-4000-8000-000000000047",
    avatar: "MJ",
    department: "Services - Testing",
    designation: "DevSecOps Practitioner - I",
    roleKey: "Testing-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0048",
    code: "TK-0048",
    label: "Red Team Practitioner - II",
    category: "Services - Testing",
    email: "dev@acme.co",
    name: "Dev Patel",
    id: "00000000-0000-4000-8000-000000000048",
    avatar: "DP",
    department: "Services - Testing",
    designation: "Red Team Practitioner - II",
    roleKey: "Testing-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TK-0049",
    code: "TK-0049",
    label: "Senior Pentester - I",
    category: "Services - Testing",
    email: "kavya@acme.co",
    name: "Kavya Nair",
    id: "00000000-0000-4000-8000-000000000049",
    avatar: "KN",
    department: "Services - Testing",
    designation: "Senior Pentester - I",
    roleKey: "Testing-Team Member",
    permissions: DEFAULT_ROLE_PERMISSIONS["Testing-Team Member" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0001",
    code: "TKI-0001",
    label: "Intern",
    category: "Services - Testing",
    email: "ananya.verma@acme.co",
    name: "Ananya Verma",
    id: "00000000-0000-4000-8000-000000000050",
    avatar: "AV",
    department: "Services - Testing",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0002",
    code: "TKI-0002",
    label: "Intern",
    category: "Services - Testing",
    email: "rohan.joshi@acme.co",
    name: "Rohan Joshi",
    id: "00000000-0000-4000-8000-000000000051",
    avatar: "RJ",
    department: "Services - Testing",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0003",
    code: "TKI-0003",
    label: "Intern",
    category: "Services - Testing",
    email: "tanvi.deshmukh@acme.co",
    name: "Tanvi Deshmukh",
    id: "00000000-0000-4000-8000-000000000052",
    avatar: "TD",
    department: "Services - Testing",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0004",
    code: "TKI-0004",
    label: "Intern",
    category: "Services - Operations",
    email: "ayush.saxena@acme.co",
    name: "Ayush Saxena",
    id: "00000000-0000-4000-8000-000000000053",
    avatar: "AS",
    department: "Services - Operations",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0005",
    code: "TKI-0005",
    label: "Intern",
    category: "Services - Operations",
    email: "simran.kaur@acme.co",
    name: "Simran Kaur",
    id: "00000000-0000-4000-8000-000000000054",
    avatar: "SK",
    department: "Services - Operations",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0006",
    code: "TKI-0006",
    label: "Intern",
    category: "Services - Consulting",
    email: "naveen.choudhary@acme.co",
    name: "Naveen Choudhary",
    id: "00000000-0000-4000-8000-000000000055",
    avatar: "NC",
    department: "Services - Consulting",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0007",
    code: "TKI-0007",
    label: "Intern",
    category: "Services - Consulting",
    email: "bhavna.patel@acme.co",
    name: "Bhavna Patel",
    id: "00000000-0000-4000-8000-000000000056",
    avatar: "BP",
    department: "Services - Consulting",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0008",
    code: "TKI-0008",
    label: "Intern",
    category: "R&D (Research & Development)",
    email: "harsh.wardhan@acme.co",
    name: "Harsh Wardhan",
    id: "00000000-0000-4000-8000-000000000057",
    avatar: "HW",
    department: "R&D (Research & Development)",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0009",
    code: "TKI-0009",
    label: "Intern",
    category: "Functional - Sales",
    email: "akash.jain@acme.co",
    name: "Akash Jain",
    id: "00000000-0000-4000-8000-000000000058",
    avatar: "AJ",
    department: "Functional - Sales",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
  {
    key: "TKI-0010",
    code: "TKI-0010",
    label: "Intern",
    category: "Functional - IT Administration",
    email: "kunal.mehra@acme.co",
    name: "Kunal Mehra",
    id: "00000000-0000-4000-8000-000000000059",
    avatar: "KM",
    department: "Functional - IT Administration",
    designation: "Intern",
    roleKey: "Intern",
    permissions: DEFAULT_ROLE_PERMISSIONS["Intern" as keyof typeof DEFAULT_ROLE_PERMISSIONS] ?? [],
  },
];

export function isDemoRoleKey(value: string | null | undefined): boolean {
  if (!value) return false;
  const normalized = value.trim().toLowerCase();
  return DEMO_PERSONAS.some(
    (p) =>
      p.key.toLowerCase() === normalized ||
      p.code.toLowerCase() === normalized ||
      p.email.toLowerCase() === normalized ||
      p.roleKey.toLowerCase() === normalized ||
      p.id.toLowerCase() === normalized,
  );
}

export function getStoredDemoRole(): string {
  if (typeof window === "undefined") return "TK-0001";
  const stored = window.localStorage.getItem(DEMO_ROLE_STORAGE_KEY);
  return isDemoRoleKey(stored) ? stored! : "TK-0001";
}

export function setStoredDemoRole(roleOrKey: string): void {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(DEMO_ROLE_STORAGE_KEY, roleOrKey);
}

export function getDemoPersona(roleOrKey: string): DemoPersona {
  const normalized = (roleOrKey || "").trim().toLowerCase();
  return (
    DEMO_PERSONAS.find(
      (p) =>
        p.key.toLowerCase() === normalized ||
        p.code.toLowerCase() === normalized ||
        p.email.toLowerCase() === normalized,
    ) ??
    DEMO_PERSONAS.find(
      (p) =>
        p.roleKey.toLowerCase() === normalized ||
        p.label.toLowerCase() === normalized,
    ) ??
    DEMO_PERSONAS[0]
  );
}

export function mockAuthUser(roleOrKey: string): AuthUser {
  const persona = getDemoPersona(roleOrKey);
  return {
    id: persona.id,
    email: persona.email,
    name: persona.name,
    role: persona.roleKey,
    mustChangePassword: false,
    permissions: persona.permissions,
  };
}
