export interface RailwayStationOption {
  value: string;
  label: string;
  subLabel: string;
  line: "Western Line" | "Central Line" | "Harbour Line" | "Trans-Harbour Line";
}

/**
 * Complete list of Mumbai suburban railway stations across all four corridors:
 * Western Line, Central Line, Harbour Line, and Trans-Harbour Line.
 */
export const MUMBAI_RAILWAY_STATIONS: RailwayStationOption[] = [
  // ── Western Line ─────────────────────────────────────────────────────────────
  { value: "Churchgate (Western Line)", label: "Churchgate", subLabel: "Western Line", line: "Western Line" },
  { value: "Marine Lines (Western Line)", label: "Marine Lines", subLabel: "Western Line", line: "Western Line" },
  { value: "Charni Road (Western Line)", label: "Charni Road", subLabel: "Western Line", line: "Western Line" },
  { value: "Grant Road (Western Line)", label: "Grant Road", subLabel: "Western Line", line: "Western Line" },
  { value: "Mumbai Central (Western Line)", label: "Mumbai Central", subLabel: "Western Line", line: "Western Line" },
  { value: "Mahalaxmi (Western Line)", label: "Mahalaxmi", subLabel: "Western Line", line: "Western Line" },
  { value: "Lower Parel (Western Line)", label: "Lower Parel", subLabel: "Western Line", line: "Western Line" },
  { value: "Prabhadevi (Western Line)", label: "Prabhadevi", subLabel: "Western Line", line: "Western Line" },
  { value: "Dadar (Western Line)", label: "Dadar", subLabel: "Western Line", line: "Western Line" },
  { value: "Matunga Road (Western Line)", label: "Matunga Road", subLabel: "Western Line", line: "Western Line" },
  { value: "Mahim (Western Line)", label: "Mahim", subLabel: "Western Line", line: "Western Line" },
  { value: "Bandra (Western Line)", label: "Bandra", subLabel: "Western Line", line: "Western Line" },
  { value: "Khar Road (Western Line)", label: "Khar Road", subLabel: "Western Line", line: "Western Line" },
  { value: "Santacruz (Western Line)", label: "Santacruz", subLabel: "Western Line", line: "Western Line" },
  { value: "Vile Parle (Western Line)", label: "Vile Parle", subLabel: "Western Line", line: "Western Line" },
  { value: "Andheri (Western Line)", label: "Andheri", subLabel: "Western Line", line: "Western Line" },
  { value: "Jogeshwari (Western Line)", label: "Jogeshwari", subLabel: "Western Line", line: "Western Line" },
  { value: "Ram Mandir (Western Line)", label: "Ram Mandir", subLabel: "Western Line", line: "Western Line" },
  { value: "Goregaon (Western Line)", label: "Goregaon", subLabel: "Western Line", line: "Western Line" },
  { value: "Malad (Western Line)", label: "Malad", subLabel: "Western Line", line: "Western Line" },
  { value: "Kandivali (Western Line)", label: "Kandivali", subLabel: "Western Line", line: "Western Line" },
  { value: "Borivali (Western Line)", label: "Borivali", subLabel: "Western Line", line: "Western Line" },
  { value: "Dahisar (Western Line)", label: "Dahisar", subLabel: "Western Line", line: "Western Line" },
  { value: "Mira Road (Western Line)", label: "Mira Road", subLabel: "Western Line", line: "Western Line" },
  { value: "Bhayandar (Western Line)", label: "Bhayandar", subLabel: "Western Line", line: "Western Line" },
  { value: "Naigaon (Western Line)", label: "Naigaon", subLabel: "Western Line", line: "Western Line" },
  { value: "Vasai Road (Western Line)", label: "Vasai Road", subLabel: "Western Line", line: "Western Line" },
  { value: "Nallasopara (Western Line)", label: "Nallasopara", subLabel: "Western Line", line: "Western Line" },
  { value: "Virar (Western Line)", label: "Virar", subLabel: "Western Line", line: "Western Line" },
  { value: "Vaitarna (Western Line)", label: "Vaitarna", subLabel: "Western Line", line: "Western Line" },
  { value: "Saphale (Western Line)", label: "Saphale", subLabel: "Western Line", line: "Western Line" },
  { value: "Kelve Road (Western Line)", label: "Kelve Road", subLabel: "Western Line", line: "Western Line" },
  { value: "Palghar (Western Line)", label: "Palghar", subLabel: "Western Line", line: "Western Line" },
  { value: "Umroli (Western Line)", label: "Umroli", subLabel: "Western Line", line: "Western Line" },
  { value: "Boisar (Western Line)", label: "Boisar", subLabel: "Western Line", line: "Western Line" },
  { value: "Vangaon (Western Line)", label: "Vangaon", subLabel: "Western Line", line: "Western Line" },
  { value: "Dahanu Road (Western Line)", label: "Dahanu Road", subLabel: "Western Line", line: "Western Line" },

  // ── Central Line ─────────────────────────────────────────────────────────────
  { value: "CSMT (Central Line)", label: "CSMT (Chhatrapati Shivaji Maharaj Terminus)", subLabel: "Central Line", line: "Central Line" },
  { value: "Masjid (Central Line)", label: "Masjid", subLabel: "Central Line", line: "Central Line" },
  { value: "Sandhurst Road (Central Line)", label: "Sandhurst Road", subLabel: "Central Line", line: "Central Line" },
  { value: "Byculla (Central Line)", label: "Byculla", subLabel: "Central Line", line: "Central Line" },
  { value: "Chinchpokli (Central Line)", label: "Chinchpokli", subLabel: "Central Line", line: "Central Line" },
  { value: "Currey Road (Central Line)", label: "Currey Road", subLabel: "Central Line", line: "Central Line" },
  { value: "Parel (Central Line)", label: "Parel", subLabel: "Central Line", line: "Central Line" },
  { value: "Dadar (Central Line)", label: "Dadar", subLabel: "Central Line", line: "Central Line" },
  { value: "Matunga (Central Line)", label: "Matunga", subLabel: "Central Line", line: "Central Line" },
  { value: "Sion (Central Line)", label: "Sion", subLabel: "Central Line", line: "Central Line" },
  { value: "Kurla (Central Line)", label: "Kurla", subLabel: "Central Line", line: "Central Line" },
  { value: "Vidyavihar (Central Line)", label: "Vidyavihar", subLabel: "Central Line", line: "Central Line" },
  { value: "Ghatkopar (Central Line)", label: "Ghatkopar", subLabel: "Central Line", line: "Central Line" },
  { value: "Vikhroli (Central Line)", label: "Vikhroli", subLabel: "Central Line", line: "Central Line" },
  { value: "Kanjurmarg (Central Line)", label: "Kanjurmarg", subLabel: "Central Line", line: "Central Line" },
  { value: "Bhandup (Central Line)", label: "Bhandup", subLabel: "Central Line", line: "Central Line" },
  { value: "Nahur (Central Line)", label: "Nahur", subLabel: "Central Line", line: "Central Line" },
  { value: "Mulund (Central Line)", label: "Mulund", subLabel: "Central Line", line: "Central Line" },
  { value: "Thane (Central Line)", label: "Thane", subLabel: "Central Line", line: "Central Line" },
  { value: "Kalwa (Central Line)", label: "Kalwa", subLabel: "Central Line", line: "Central Line" },
  { value: "Mumbra (Central Line)", label: "Mumbra", subLabel: "Central Line", line: "Central Line" },
  { value: "Diva (Central Line)", label: "Diva", subLabel: "Central Line", line: "Central Line" },
  { value: "Kopar (Central Line)", label: "Kopar", subLabel: "Central Line", line: "Central Line" },
  { value: "Dombivli (Central Line)", label: "Dombivli", subLabel: "Central Line", line: "Central Line" },
  { value: "Thakurli (Central Line)", label: "Thakurli", subLabel: "Central Line", line: "Central Line" },
  { value: "Kalyan (Central Line)", label: "Kalyan", subLabel: "Central Line", line: "Central Line" },
  // Beyond Kalyan - Kasara Branch
  { value: "Shahad (Central Line)", label: "Shahad", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Ambivli (Central Line)", label: "Ambivli", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Titwala (Central Line)", label: "Titwala", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Khadavli (Central Line)", label: "Khadavli", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Vasind (Central Line)", label: "Vasind", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Asangaon (Central Line)", label: "Asangaon", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Atgaon (Central Line)", label: "Atgaon", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Thansit (Central Line)", label: "Thansit", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Khardi (Central Line)", label: "Khardi", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Umbermali (Central Line)", label: "Umbermali", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  { value: "Kasara (Central Line)", label: "Kasara", subLabel: "Central Line (Kasara Branch)", line: "Central Line" },
  // Beyond Kalyan - Karjat / Khopoli Branch
  { value: "Vithalwadi (Central Line)", label: "Vithalwadi", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Ulhasnagar (Central Line)", label: "Ulhasnagar", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Ambernath (Central Line)", label: "Ambernath", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Badlapur (Central Line)", label: "Badlapur", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Vangani (Central Line)", label: "Vangani", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Shelu (Central Line)", label: "Shelu", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Neral (Central Line)", label: "Neral", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Bhivpuri Road (Central Line)", label: "Bhivpuri Road", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Karjat (Central Line)", label: "Karjat", subLabel: "Central Line (Karjat Branch)", line: "Central Line" },
  { value: "Palasdari (Central Line)", label: "Palasdari", subLabel: "Central Line (Khopoli Branch)", line: "Central Line" },
  { value: "Kelavli (Central Line)", label: "Kelavli", subLabel: "Central Line (Khopoli Branch)", line: "Central Line" },
  { value: "Dolavli (Central Line)", label: "Dolavli", subLabel: "Central Line (Khopoli Branch)", line: "Central Line" },
  { value: "Lowjee (Central Line)", label: "Lowjee", subLabel: "Central Line (Khopoli Branch)", line: "Central Line" },
  { value: "Khopoli (Central Line)", label: "Khopoli", subLabel: "Central Line (Khopoli Branch)", line: "Central Line" },

  // ── Harbour Line ─────────────────────────────────────────────────────────────
  { value: "CSMT (Harbour Line)", label: "CSMT (Chhatrapati Shivaji Maharaj Terminus)", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Masjid (Harbour Line)", label: "Masjid", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Sandhurst Road (Harbour Line)", label: "Sandhurst Road", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Dockyard Road (Harbour Line)", label: "Dockyard Road", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Reay Road (Harbour Line)", label: "Reay Road", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Cotton Green (Harbour Line)", label: "Cotton Green", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Sewri (Harbour Line)", label: "Sewri", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Vadala Road (Harbour Line)", label: "Vadala Road", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Kings Circle (Harbour Line)", label: "Kings Circle", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "GTB Nagar (Harbour Line)", label: "GTB Nagar (Guru Tegh Bahadur Nagar)", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Chunabhatti (Harbour Line)", label: "Chunabhatti", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Kurla (Harbour Line)", label: "Kurla", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Tilak Nagar (Harbour Line)", label: "Tilak Nagar", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Chembur (Harbour Line)", label: "Chembur", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Govandi (Harbour Line)", label: "Govandi", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Mankhurd (Harbour Line)", label: "Mankhurd", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Vashi (Harbour Line)", label: "Vashi", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Sanpada (Harbour Line)", label: "Sanpada", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Juinagar (Harbour Line)", label: "Juinagar", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Nerul (Harbour Line)", label: "Nerul", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Seawoods-Darave (Harbour Line)", label: "Seawoods-Darave", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "CBD Belapur (Harbour Line)", label: "CBD Belapur", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Kharghar (Harbour Line)", label: "Kharghar", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Mansarovar (Harbour Line)", label: "Mansarovar", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Khandeshwar (Harbour Line)", label: "Khandeshwar", subLabel: "Harbour Line", line: "Harbour Line" },
  { value: "Panvel (Harbour Line)", label: "Panvel", subLabel: "Harbour Line", line: "Harbour Line" },

  // ── Trans-Harbour Line ───────────────────────────────────────────────────────
  { value: "Thane (Trans-Harbour Line)", label: "Thane", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Digha Gaon (Trans-Harbour Line)", label: "Digha Gaon", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Airoli (Trans-Harbour Line)", label: "Airoli", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Rabale (Trans-Harbour Line)", label: "Rabale", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Ghansoli (Trans-Harbour Line)", label: "Ghansoli", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Kopar Khairane (Trans-Harbour Line)", label: "Kopar Khairane", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Turbhe (Trans-Harbour Line)", label: "Turbhe", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Sanpada (Trans-Harbour Line)", label: "Sanpada", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Vashi (Trans-Harbour Line)", label: "Vashi", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Juinagar (Trans-Harbour Line)", label: "Juinagar", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Nerul (Trans-Harbour Line)", label: "Nerul", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Seawoods-Darave (Trans-Harbour Line)", label: "Seawoods-Darave", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "CBD Belapur (Trans-Harbour Line)", label: "CBD Belapur", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
  { value: "Panvel (Trans-Harbour Line)", label: "Panvel", subLabel: "Trans-Harbour Line", line: "Trans-Harbour Line" },
];
