namespace PMS.API.Modules.Resources.DTOs;

public sealed record EmployeeListItemDto(
    Guid Id,
    string EmployeeCode,
    string FullName,
    string WorkEmail,
    string? Department,
    string? Designation,
    string? ReportingManagerName,
    DateOnly? JoiningDate,
    string? WorkLocation,
    string? OfficeBranch,
    string? Category,
    string? ProjectSite,
    decimal? KpiScore,
    string? Status,
    DateTime CreatedAtUtc,
    string? PersonalEmail = null,
    string? Phone = null,
    string? AltPhone = null,
    string? EmergencyContact = null,
    string? EmergencyContactName = null,
    string? EmergencyContactRelation = null,
    string? Pan = null,
    string? BankAccount = null,
    string? PfUan = null,
    string? Education = null,
    IReadOnlyList<string>? Skills = null,
    IReadOnlyList<string>? Certifications = null,
    IReadOnlyList<string>? Languages = null,
    string? Role = null,
    string? BusinessUnit = null,
    string? Team = null,
    string? Experience = null,
    string? PreviousCompany = null,
    string? PmoDepartment = null,
    string? SubDepartment = null,
    string? BillableStatus = null,
    string? ClientLocation = null,
    string? ProjectType = null,
    string? ProjectAllocated = null,
    string? ClientEngManagerMapping = null);

public sealed record EmployeeDetailDto(
    Guid Id,
    string EmployeeCode,
    string FirstName,
    string LastName,
    string WorkEmail,
    string? PersonalEmail,
    string? Phone,
    string? AltPhone,
    string? Gender,
    DateOnly? DateOfBirth,
    string? Address,
    string? EmergencyContact,
    string? EmergencyContactName,
    string? EmergencyContactRelation,
    string? MaritalStatus,
    string? Nationality,
    string? Department,
    string? Designation,
    string? Role,
    Guid? ReportingManagerId,
    string? ReportingManagerName,
    string? BusinessUnit,
    string? WorkLocation,
    string? OfficeBranch,
    string? Category,
    string? Team,
    DateOnly? JoiningDate,
    string? Status,
    string? ConfirmationStatus,
    string? ProbationStatus,
    string? Experience,
    string? PreviousCompany,
    string? EmploymentType,
    string? ContractType,
    string? BondStatus,
    string? NoticePeriod,
    string? ProjectSite,
    string? AssetId,
    string? ExitType,
    string? ExitReason,
    string? Education,
    IReadOnlyList<string> Skills,
    IReadOnlyList<string> Certifications,
    IReadOnlyList<string> Languages,
    decimal? KpiScore,
    decimal? QuarterlyKpi,
    decimal? AnnualRating,
    decimal? GoalCompletion,
    decimal? Attendance,
    decimal? ReportingEfficiency,
    string? PromotionReadiness,
    string? ManagerFeedback,
    string? Pan,
    string? Aadhaar,
    string? BankAccount,
    string? SalaryBand,
    string? PfUan,
    string? TaxRegime = null,
    string? ComplianceStatus = null,
    string? PmoDepartment = null,
    string? SubDepartment = null,
    string? BillableStatus = null,
    string? ClientLocation = null,
    string? ProjectType = null,
    string? ProjectAllocated = null,
    string? ClientEngManagerMapping = null,
    string? GradDegree = null,
    string? GradYear = null,
    string? PostGradDegree = null,
    string? PostGradYear = null,
    string? ExpType = null,
    string? PriorTotalExp = null,
    string? PriorRelevantExp = null,
    string? BondDelivered = null,
    int? BondDurationMonths = null,
    DateOnly? BondExpiryDate = null,
    Guid? EmployeeStatusId = null,
    Guid? DepartmentId = null,
    Guid? DesignationId = null,
    Guid? JobRoleId = null);

public sealed record EmployeeLookupDto(
    Guid Id,
    string EmployeeCode,
    string FullName,
    string? Department,
    string? Designation,
    string? Status,
    string WorkEmail);

public sealed record ExitedEmployeeDto(
    Guid Id,
    Guid OriginalEmployeeId,
    string EmployeeCode,
    string FullName,
    DateOnly? LastWorkingDay,
    string? ExitType,
    string? ExitReason,
    DateTime ExitedAtUtc,
    string? DepartmentName,
    string? DesignationName,
    string? ReasonForLeaving);

public sealed record MetaOptionDto(Guid Id, string Code, string Name, Guid? ParentId = null);

public sealed record CreateCatalogItemRequest(string Name, Guid? ParentId = null);

public sealed record CreateEmployeeRequest(
    string EmployeeCode,
    string FirstName,
    string LastName,
    string WorkEmail,
    string? PersonalEmail = null,
    string? Phone = null,
    string? AltPhone = null,
    string? Gender = null,
    DateOnly? DateOfBirth = null,
    string? Address = null,
    string? EmergencyContact = null,
    string? EmergencyContactName = null,
    string? MaritalStatus = null,
    string? Nationality = null,
    Guid? NationalityId = null,
    Guid? DepartmentId = null,
    Guid? DesignationId = null,
    string? Role = null,
    Guid? JobRoleId = null,
    Guid? ReportingManagerId = null,
    string? BusinessUnit = null,
    string? WorkLocation = null,
    string? OfficeBranch = null,
    string? Category = null,
    string? Team = null,
    DateOnly? JoiningDate = null,
    string? Status = null,
    string? ConfirmationStatus = null,
    string? ProbationStatus = null,
    string? Experience = null,
    string? PreviousCompany = null,
    string? EmploymentType = null,
    string? ContractType = null,
    string? BondStatus = null,
    string? NoticePeriod = null,
    string? ProjectSite = null,
    string? AssetId = null,
    string? ExitType = null,
    string? ExitReason = null,
    string? Education = null,
    List<string>? Skills = null,
    List<string>? Certifications = null,
    List<string>? Languages = null,
    decimal? KpiScore = null,
    decimal? QuarterlyKpi = null,
    decimal? AnnualRating = null,
    decimal? GoalCompletion = null,
    decimal? Attendance = null,
    decimal? ReportingEfficiency = null,
    string? PromotionReadiness = null,
    string? ManagerFeedback = null,
    string? Pan = null,
    string? BankAccount = null,
    string? SalaryBand = null,
    string? PfUan = null,
    string? TaxRegime = null,
    string? ComplianceStatus = null,
    Guid? SalaryBandId = null,
    string? ProbationPeriod = null,
    string? Aadhaar = null,
    Guid? EmployeeStatusId = null,
    string? BondDelivered = null,
    int? BondDurationMonths = null,
    DateOnly? BondExpiryDate = null,
    string? EmergencyContactRelation = null,
    string? PmoDepartment = null,
    string? SubDepartment = null,
    string? BillableStatus = null,
    string? ClientLocation = null,
    string? ProjectType = null,
    string? ProjectAllocated = null,
    string? ClientEngManagerMapping = null,
    string? GradDegree = null,
    string? GradYear = null,
    string? PostGradDegree = null,
    string? PostGradYear = null,
    string? ExpType = null,
    string? PriorTotalExp = null,
    string? PriorRelevantExp = null);

public sealed record UpdateEmployeeRequest(
    string? FirstName = null,
    string? LastName = null,
    string? WorkEmail = null,
    string? PersonalEmail = null,
    string? Phone = null,
    string? AltPhone = null,
    string? Gender = null,
    DateOnly? DateOfBirth = null,
    string? Address = null,
    string? EmergencyContact = null,
    string? EmergencyContactName = null,
    string? MaritalStatus = null,
    string? Nationality = null,
    Guid? NationalityId = null,
    Guid? DepartmentId = null,
    Guid? DesignationId = null,
    string? Department = null,
    string? Designation = null,
    string? Role = null,
    Guid? JobRoleId = null,
    Guid? ReportingManagerId = null,
    string? BusinessUnit = null,
    string? WorkLocation = null,
    string? OfficeBranch = null,
    string? Category = null,
    string? Team = null,
    DateOnly? JoiningDate = null,
    string? Status = null,
    string? ConfirmationStatus = null,
    string? ProbationStatus = null,
    string? Experience = null,
    string? PreviousCompany = null,
    string? EmploymentType = null,
    string? ContractType = null,
    string? BondStatus = null,
    string? NoticePeriod = null,
    string? ProjectSite = null,
    string? AssetId = null,
    string? ExitType = null,
    string? ExitReason = null,
    string? Education = null,
    List<string>? Skills = null,
    List<string>? Certifications = null,
    List<string>? Languages = null,
    decimal? KpiScore = null,
    decimal? QuarterlyKpi = null,
    decimal? AnnualRating = null,
    decimal? GoalCompletion = null,
    decimal? Attendance = null,
    decimal? ReportingEfficiency = null,
    string? PromotionReadiness = null,
    string? ManagerFeedback = null,
    string? Pan = null,
    string? BankAccount = null,
    string? SalaryBand = null,
    string? PfUan = null,
    string? TaxRegime = null,
    string? ComplianceStatus = null,
    Guid? SalaryBandId = null,
    string? ProbationPeriod = null,
    string? Aadhaar = null,
    string? EmployeeCode = null,
    string? EmergencyContactRelation = null,
    string? PmoDepartment = null,
    string? SubDepartment = null,
    string? BillableStatus = null,
    string? ClientLocation = null,
    string? ProjectType = null,
    string? ProjectAllocated = null,
    string? ClientEngManagerMapping = null,
    string? GradDegree = null,
    string? GradYear = null,
    string? PostGradDegree = null,
    string? PostGradYear = null,
    string? ExpType = null,
    string? PriorTotalExp = null,
    string? PriorRelevantExp = null,
    string? BondDelivered = null,
    int? BondDurationMonths = null,
    DateOnly? BondExpiryDate = null,
    Guid? EmployeeStatusId = null);

public sealed record EmployeeBulkRowError(int Row, string? EmployeeCode, string Message);

public sealed class EmployeeBulkUploadRequest
{
    public IFormFile File { get; set; } = null!;
}

public sealed record EmployeeBulkUploadResult(
    int Created,
    int Failed,
    IReadOnlyList<EmployeeBulkRowError> Errors);

public sealed record OffboardEmployeeRequest(
    DateOnly? ResignationDate,
    DateOnly? LastWorkingDay,
    string? ReasonForLeaving,
    string? NoticePeriodServed,
    string? ExitChecklistJson,
    string? AssetReturnJson,
    string? FinalSettlementJson,
    string? ExitType,
    string? ExitReason);
