namespace PMS.API.Modules.Resources.DTOs;

public sealed record EmployeeListItemDto(
    Guid Id,
    string EmployeeCode,
    string FullName,
    string WorkEmail,
    string? Department,
    string? Designation,
    string? ReportingManagerName,
    DateOnly? JoiningDate,
    string? WorkLocation,
    string? OfficeBranch,
    string? Category,
    string? ProjectSite,
    decimal? KpiScore,
    string? Status,
    DateTime CreatedAtUtc,
    string? PersonalEmail = null,
    string? Phone = null,
    string? AltPhone = null,
    string? EmergencyContact = null,
    string? Pan = null,
    string? BankAccount = null,
    string? PfUan = null,
    string? Education = null,
    IReadOnlyList<string>? Skills = null,
    IReadOnlyList<string>? Certifications = null,
    IReadOnlyList<string>? Languages = null,
    string? Role = null,
    string? BusinessUnit = null,
    string? Team = null,
    string? Experience = null,
    string? PreviousCompany = null);

public sealed record EmployeeDetailDto(
    Guid Id,
    string EmployeeCode,
    string FirstName,
    string LastName,
    string WorkEmail,
    string? PersonalEmail,
    string? Phone,
    string? AltPhone,
    string? Gender,
    DateOnly? DateOfBirth,
    string? Address,
    string? EmergencyContact,
    string? MaritalStatus,
    string? Nationality,
    string? Department,
    string? Designation,
    string? Role,
    Guid? ReportingManagerId,
    string? ReportingManagerName,
    string? BusinessUnit,
    string? WorkLocation,
    string? OfficeBranch,
    string? Category,
    string? Team,
    DateOnly? JoiningDate,
    string? Status,
    string? ConfirmationStatus,
    string? ProbationStatus,
    string? Experience,
    string? PreviousCompany,
    string? EmploymentType,
    string? ContractType,
    string? BondStatus,
    string? NoticePeriod,
    string? ProjectSite,
    string? AssetId,
    string? ExitType,
    string? ExitReason,
    string? Education,
    IReadOnlyList<string> Skills,
    IReadOnlyList<string> Certifications,
    IReadOnlyList<string> Languages,
    decimal? KpiScore,
    decimal? QuarterlyKpi,
    decimal? AnnualRating,
    decimal? GoalCompletion,
    decimal? Attendance,
    decimal? ReportingEfficiency,
    string? PromotionReadiness,
    string? ManagerFeedback,
    string? Pan,
    string? Aadhaar,
    string? BankAccount,
    string? SalaryBand,
    string? PfUan,
    string? TaxRegime,
    string? ComplianceStatus);

public sealed record EmployeeLookupDto(
    Guid Id,
    string EmployeeCode,
    string FullName,
    string? Department,
    string? Designation,
    string? Status,
    string WorkEmail);

public sealed record ExitedEmployeeDto(
    Guid Id,
    Guid OriginalEmployeeId,
    string EmployeeCode,
    string FullName,
    DateOnly? LastWorkingDay,
    string? ExitType,
    string? ExitReason,
    DateTime ExitedAtUtc,
    string? DepartmentName,
    string? DesignationName,
    string? ReasonForLeaving);

public sealed record MetaOptionDto(Guid Id, string Code, string Name, Guid? ParentId = null);

public sealed record CreateCatalogItemRequest(string Name, Guid? ParentId = null);

public sealed record CreateEmployeeRequest(
    string EmployeeCode,
    string FirstName,
    string LastName,
    string WorkEmail,
    string? PersonalEmail,
    string? Phone,
    string? AltPhone,
    string? Gender,
    DateOnly? DateOfBirth,
    string? Address,
    string? EmergencyContact,
    string? MaritalStatus,
    string? Nationality,
    Guid? NationalityId,
    Guid? DepartmentId,
    Guid? DesignationId,
    string? Role,
    Guid? JobRoleId,
    Guid? ReportingManagerId,
    string? BusinessUnit,
    string? WorkLocation,
    string? OfficeBranch,
    string? Category,
    string? Team,
    DateOnly? JoiningDate,
    string? Status,
    string? ConfirmationStatus,
    string? ProbationStatus,
    string? Experience,
    string? PreviousCompany,
    string? EmploymentType,
    string? ContractType,
    string? BondStatus,
    string? NoticePeriod,
    string? ProjectSite,
    string? AssetId,
    string? ExitType,
    string? ExitReason,
    string? Education,
    List<string>? Skills,
    List<string>? Certifications,
    List<string>? Languages,
    decimal? KpiScore,
    decimal? QuarterlyKpi,
    decimal? AnnualRating,
    decimal? GoalCompletion,
    decimal? Attendance,
    decimal? ReportingEfficiency,
    string? PromotionReadiness,
    string? ManagerFeedback,
    string? Pan,
    string? BankAccount,
    string? SalaryBand,
    string? PfUan,
    string? TaxRegime,
    string? ComplianceStatus,
    Guid? SalaryBandId = null,
    string? ProbationPeriod = null,
    string? Aadhaar = null);

public sealed record UpdateEmployeeRequest(
    string? FirstName,
    string? LastName,
    string? WorkEmail,
    string? PersonalEmail,
    string? Phone,
    string? AltPhone,
    string? Gender,
    DateOnly? DateOfBirth,
    string? Address,
    string? EmergencyContact,
    string? MaritalStatus,
    string? Nationality,
    Guid? NationalityId,
    Guid? DepartmentId,
    Guid? DesignationId,
    string? Department,
    string? Designation,
    string? Role,
    Guid? JobRoleId,
    Guid? ReportingManagerId,
    string? BusinessUnit,
    string? WorkLocation,
    string? OfficeBranch,
    string? Category,
    string? Team,
    DateOnly? JoiningDate,
    string? Status,
    string? ConfirmationStatus,
    string? ProbationStatus,
    string? Experience,
    string? PreviousCompany,
    string? EmploymentType,
    string? ContractType,
    string? BondStatus,
    string? NoticePeriod,
    string? ProjectSite,
    string? AssetId,
    string? ExitType,
    string? ExitReason,
    string? Education,
    List<string>? Skills,
    List<string>? Certifications,
    List<string>? Languages,
    decimal? KpiScore,
    decimal? QuarterlyKpi,
    decimal? AnnualRating,
    decimal? GoalCompletion,
    decimal? Attendance,
    decimal? ReportingEfficiency,
    string? PromotionReadiness,
    string? ManagerFeedback,
    string? Pan,
    string? BankAccount,
    string? SalaryBand,
    string? PfUan,
    string? TaxRegime,
    string? ComplianceStatus,
    Guid? SalaryBandId = null,
    string? ProbationPeriod = null,
    string? Aadhaar = null,
    string? EmployeeCode = null);

public sealed record EmployeeBulkRowError(int Row, string? EmployeeCode, string Message);

public sealed class EmployeeBulkUploadRequest
{
    public IFormFile File { get; set; } = null!;
}

public sealed record EmployeeBulkUploadResult(
    int Created,
    int Failed,
    IReadOnlyList<EmployeeBulkRowError> Errors);

public sealed record OffboardEmployeeRequest(
    DateOnly? ResignationDate,
    DateOnly? LastWorkingDay,
    string? ReasonForLeaving,
    string? NoticePeriodServed,
    string? ExitChecklistJson,
    string? AssetReturnJson,
    string? FinalSettlementJson,
    string? ExitType,
    string? ExitReason);
