export type AccessLevel = "manage" | "view" | "none";

export interface ExcelPageDefinition {
  id: string;
  colIdx: number;
  excelCol: string;
  module: string;
  submodule: string;
  page: string;
  route: string;
}

export const EXCEL_PAGE_DEFINITIONS: ExcelPageDefinition[] = [
  {
    "id": "p_1",
    "colIdx": 4,
    "excelCol": "DashBoard",
    "module": "Dashboard",
    "submodule": "Overview",
    "page": "Dashboard",
    "route": "/"
  },
  {
    "id": "p_2",
    "colIdx": 5,
    "excelCol": "Action Center > Bucket List",
    "module": "Action Center",
    "submodule": "Task Management",
    "page": "Bucket List",
    "route": "/action-centre?tab=bucket"
  },
  {
    "id": "p_3",
    "colIdx": 6,
    "excelCol": "Approvals",
    "module": "Action Center",
    "submodule": "Governance & Approvals",
    "page": "Approvals",
    "route": "/approvals"
  },
  {
    "id": "p_4",
    "colIdx": 7,
    "excelCol": "Alrets",
    "module": "Action Center",
    "submodule": "Governance & Approvals",
    "page": "Alerts",
    "route": "/action-centre?tab=alerts"
  },
  {
    "id": "p_5",
    "colIdx": 8,
    "excelCol": "Notification",
    "module": "Action Center",
    "submodule": "Governance & Approvals",
    "page": "Notification",
    "route": "/action-centre"
  },
  {
    "id": "p_6",
    "colIdx": 9,
    "excelCol": "Project > New Project",
    "module": "Project",
    "submodule": "Pipeline & Intake",
    "page": "Add New Project",
    "route": "/projects/new"
  },
  {
    "id": "p_7",
    "colIdx": 10,
    "excelCol": "Overview > Budget",
    "module": "Project",
    "submodule": "Overview",
    "page": "Budget",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_8",
    "colIdx": 11,
    "excelCol": "Extenstion Request",
    "module": "Project",
    "submodule": "Overview",
    "page": "Extension Request",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_9",
    "colIdx": 12,
    "excelCol": "Change Project Manger",
    "module": "Project",
    "submodule": "Overview",
    "page": "Change Project Manager",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_10",
    "colIdx": 13,
    "excelCol": "Change Team leader",
    "module": "Project",
    "submodule": "Overview",
    "page": "Change Team Leader",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_11",
    "colIdx": 14,
    "excelCol": "Change Sr.Project Manager",
    "module": "Project",
    "submodule": "Overview",
    "page": "Change Sr. Project Manager",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_12",
    "colIdx": 15,
    "excelCol": "WBS > PMO Intake  & Pre-requisite",
    "module": "Project",
    "submodule": "WBS",
    "page": "PMO Intake & Pre-requisite",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_13",
    "colIdx": 16,
    "excelCol": "Service and deliverable",
    "module": "Project",
    "submodule": "WBS",
    "page": "Service and Deliverable",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_14",
    "colIdx": 17,
    "excelCol": "View WBS Amount",
    "module": "Project",
    "submodule": "WBS",
    "page": "View WBS Amount",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_15",
    "colIdx": 18,
    "excelCol": "Project Allocation",
    "module": "Project",
    "submodule": "WBS",
    "page": "Project Allocation",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_16",
    "colIdx": 19,
    "excelCol": "Service wise Pre-requsite Tracking",
    "module": "Project",
    "submodule": "WBS",
    "page": "Service-wise Pre-requisite Tracking",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_17",
    "colIdx": 20,
    "excelCol": "Team > Edit Team",
    "module": "Project",
    "submodule": "Team",
    "page": "Edit Team",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_18",
    "colIdx": 21,
    "excelCol": "Task > Edit Task",
    "module": "Project",
    "submodule": "Task",
    "page": "Edit Task",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_19",
    "colIdx": 22,
    "excelCol": "Health > Issues",
    "module": "Project",
    "submodule": "Health",
    "page": "Issues",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_20",
    "colIdx": 23,
    "excelCol": "Alerts",
    "module": "Project",
    "submodule": "Health",
    "page": "Alerts",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_21",
    "colIdx": 24,
    "excelCol": "Appreciation",
    "module": "Project",
    "submodule": "Health",
    "page": "Appreciation",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_22",
    "colIdx": 25,
    "excelCol": "Customer engagement > Interview Scheduling",
    "module": "Project",
    "submodule": "Customer Engagement",
    "page": "Interview Scheduling",
    "route": "/health-interview-scheduling"
  },
  {
    "id": "p_23",
    "colIdx": 26,
    "excelCol": "Additional Customer Requirement",
    "module": "Project",
    "submodule": "Customer Engagement",
    "page": "Additional Customer Requirement",
    "route": "/health-additional-requirements"
  },
  {
    "id": "p_24",
    "colIdx": 27,
    "excelCol": "Invoice",
    "module": "Project",
    "submodule": "Invoice",
    "page": "Invoice",
    "route": "/projects/$projectId"
  },
  {
    "id": "p_25",
    "colIdx": 28,
    "excelCol": "Report > Sales Report",
    "module": "Report",
    "submodule": "Commercial Reports",
    "page": "Sales Report",
    "route": "/dh-reports"
  },
  {
    "id": "p_26",
    "colIdx": 29,
    "excelCol": "WBS Tracker",
    "module": "Report",
    "submodule": "Delivery Reports",
    "page": "WBS Tracker",
    "route": "/reports"
  },
  {
    "id": "p_27",
    "colIdx": 30,
    "excelCol": "PO Tracker",
    "module": "Report",
    "submodule": "Commercial Reports",
    "page": "PO Tracker",
    "route": "/reports"
  },
  {
    "id": "p_28",
    "colIdx": 31,
    "excelCol": "Invoice tracker",
    "module": "Report",
    "submodule": "Commercial Reports",
    "page": "Invoice Tracker",
    "route": "/reports"
  },
  {
    "id": "p_29",
    "colIdx": 32,
    "excelCol": "Resource > Directory and Pool > Directory",
    "module": "Resource",
    "submodule": "Directory and Pool",
    "page": "Directory",
    "route": "/dh-employee-directory"
  },
  {
    "id": "p_30",
    "colIdx": 33,
    "excelCol": "Resource Pool",
    "module": "Resource",
    "submodule": "Directory and Pool",
    "page": "Resource Pool",
    "route": "/dh-resource-pool"
  },
  {
    "id": "p_31",
    "colIdx": 34,
    "excelCol": "Add Employee",
    "module": "Resource",
    "submodule": "Directory and Pool",
    "page": "Add Employee",
    "route": "/dh-employee-directory"
  },
  {
    "id": "p_32",
    "colIdx": 35,
    "excelCol": "Exit Summary",
    "module": "Resource",
    "submodule": "Exit Summary",
    "page": "Exit Summary",
    "route": "/dh-exit-summary"
  },
  {
    "id": "p_33",
    "colIdx": 36,
    "excelCol": "Customer > Customer onboarding",
    "module": "Customer",
    "submodule": "Customer Onboarding",
    "page": "Customer Onboarding",
    "route": "/customers"
  },
  {
    "id": "p_34",
    "colIdx": 37,
    "excelCol": "Customer sub venture project Profile > Edit Sales Manager",
    "module": "Customer",
    "submodule": "Customer Sub Venture Project Profile",
    "page": "Edit Sales Manager",
    "route": "/customers/$clientId"
  },
  {
    "id": "p_35",
    "colIdx": 38,
    "excelCol": "Edit Enagement Manager",
    "module": "Customer",
    "submodule": "Customer Sub Venture Project Profile",
    "page": "Edit Engagement Manager",
    "route": "/customers/$clientId"
  },
  {
    "id": "p_36",
    "colIdx": 39,
    "excelCol": "My Team > Team Dashboard",
    "module": "My Team",
    "submodule": "Team Dashboard",
    "page": "Team Dashboard",
    "route": "/my-team"
  },
  {
    "id": "p_37",
    "colIdx": 40,
    "excelCol": "Timesheet > My timesheet",
    "module": "My Team",
    "submodule": "Timesheet",
    "page": "My Timesheet",
    "route": "/timesheet"
  },
  {
    "id": "p_38",
    "colIdx": 41,
    "excelCol": "Timesheet Approval",
    "module": "My Team",
    "submodule": "Timesheet",
    "page": "Timesheet Approval",
    "route": "/my-team/timesheets"
  },
  {
    "id": "p_39",
    "colIdx": 42,
    "excelCol": "Repository > Upload Docs",
    "module": "Repository",
    "submodule": "Document Management",
    "page": "Upload Docs",
    "route": "/my-org"
  },
  {
    "id": "p_40",
    "colIdx": 43,
    "excelCol": "Delete Docs",
    "module": "Repository",
    "submodule": "Document Management",
    "page": "Delete Docs",
    "route": "/my-org"
  },
  {
    "id": "p_41",
    "colIdx": 44,
    "excelCol": "Setting > Module wise Acess",
    "module": "Setting",
    "submodule": "Security & Access",
    "page": "Module-wise Access",
    "route": "/dh-settings-security-roles"
  },
  {
    "id": "p_42",
    "colIdx": 45,
    "excelCol": "User Role Access",
    "module": "Setting",
    "submodule": "Security & Access",
    "page": "User Role Access",
    "route": "/dh-settings-security-roles"
  },
  {
    "id": "p_43",
    "colIdx": 46,
    "excelCol": "Master (Project, customer, Resorce)",
    "module": "Setting",
    "submodule": "Master Data",
    "page": "Master (Project, Customer, Resource)",
    "route": "/dh-settings-masters"
  }
];

export const EXCEL_ROLE_BASELINES: Record<string, Record<string, AccessLevel>> = {
  "Team Member": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "view",
    "p_4": "view",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "none",
    "p_9": "none",
    "p_10": "none",
    "p_11": "none",
    "p_12": "none",
    "p_13": "none",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "none",
    "p_18": "none",
    "p_19": "none",
    "p_20": "none",
    "p_21": "none",
    "p_22": "none",
    "p_23": "none",
    "p_24": "none",
    "p_25": "none",
    "p_26": "none",
    "p_27": "none",
    "p_28": "none",
    "p_29": "none",
    "p_30": "none",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "none",
    "p_35": "none",
    "p_36": "view",
    "p_37": "manage",
    "p_38": "view",
    "p_39": "view",
    "p_40": "view",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Team Lead": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "view",
    "p_4": "view",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "none",
    "p_9": "none",
    "p_10": "none",
    "p_11": "none",
    "p_12": "none",
    "p_13": "view",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "view",
    "p_18": "manage",
    "p_19": "view",
    "p_20": "view",
    "p_21": "view",
    "p_22": "view",
    "p_23": "view",
    "p_24": "none",
    "p_25": "none",
    "p_26": "view",
    "p_27": "view",
    "p_28": "none",
    "p_29": "view",
    "p_30": "manage",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "none",
    "p_35": "none",
    "p_36": "manage",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "view",
    "p_40": "view",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Manager (Project Manager)": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "manage",
    "p_9": "view",
    "p_10": "manage",
    "p_11": "none",
    "p_12": "none",
    "p_13": "view",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "manage",
    "p_18": "manage",
    "p_19": "manage",
    "p_20": "manage",
    "p_21": "manage",
    "p_22": "view",
    "p_23": "manage",
    "p_24": "none",
    "p_25": "none",
    "p_26": "view",
    "p_27": "view",
    "p_28": "none",
    "p_29": "view",
    "p_30": "manage",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "view",
    "p_35": "view",
    "p_36": "manage",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "view",
    "p_40": "view",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Senior Manager (Sr. Project Manager)": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "manage",
    "p_9": "view",
    "p_10": "manage",
    "p_11": "none",
    "p_12": "none",
    "p_13": "view",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "manage",
    "p_18": "manage",
    "p_19": "manage",
    "p_20": "manage",
    "p_21": "manage",
    "p_22": "view",
    "p_23": "manage",
    "p_24": "none",
    "p_25": "none",
    "p_26": "view",
    "p_27": "view",
    "p_28": "none",
    "p_29": "view",
    "p_30": "manage",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "view",
    "p_35": "view",
    "p_36": "manage",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "manage",
    "p_40": "manage",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "HOD": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "view",
    "p_8": "view",
    "p_9": "view",
    "p_10": "view",
    "p_11": "view",
    "p_12": "view",
    "p_13": "view",
    "p_14": "view",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "manage",
    "p_20": "manage",
    "p_21": "manage",
    "p_22": "view",
    "p_23": "view",
    "p_24": "view",
    "p_25": "view",
    "p_26": "view",
    "p_27": "view",
    "p_28": "view",
    "p_29": "view",
    "p_30": "manage",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "view",
    "p_35": "view",
    "p_36": "manage",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "manage",
    "p_40": "manage",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Team Member (R&D only)": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "view",
    "p_4": "view",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "none",
    "p_9": "none",
    "p_10": "none",
    "p_11": "none",
    "p_12": "none",
    "p_13": "none",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "none",
    "p_18": "none",
    "p_19": "none",
    "p_20": "none",
    "p_21": "none",
    "p_22": "none",
    "p_23": "none",
    "p_24": "none",
    "p_25": "none",
    "p_26": "none",
    "p_27": "none",
    "p_28": "none",
    "p_29": "none",
    "p_30": "none",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "none",
    "p_35": "none",
    "p_36": "view",
    "p_37": "manage",
    "p_38": "view",
    "p_39": "view",
    "p_40": "view",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "CEO": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "view",
    "p_7": "view",
    "p_8": "view",
    "p_9": "view",
    "p_10": "view",
    "p_11": "view",
    "p_12": "view",
    "p_13": "view",
    "p_14": "view",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "view",
    "p_20": "view",
    "p_21": "view",
    "p_22": "view",
    "p_23": "view",
    "p_24": "view",
    "p_25": "view",
    "p_26": "view",
    "p_27": "view",
    "p_28": "view",
    "p_29": "view",
    "p_30": "view",
    "p_31": "view",
    "p_32": "view",
    "p_33": "view",
    "p_34": "view",
    "p_35": "view",
    "p_36": "view",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "view",
    "p_40": "view",
    "p_41": "view",
    "p_42": "view",
    "p_43": "view"
  },
  "COO": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "view",
    "p_7": "view",
    "p_8": "view",
    "p_9": "view",
    "p_10": "view",
    "p_11": "view",
    "p_12": "view",
    "p_13": "view",
    "p_14": "view",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "view",
    "p_20": "view",
    "p_21": "view",
    "p_22": "view",
    "p_23": "view",
    "p_24": "view",
    "p_25": "view",
    "p_26": "view",
    "p_27": "view",
    "p_28": "view",
    "p_29": "view",
    "p_30": "view",
    "p_31": "view",
    "p_32": "view",
    "p_33": "view",
    "p_34": "view",
    "p_35": "view",
    "p_36": "view",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "view",
    "p_40": "view",
    "p_41": "view",
    "p_42": "view",
    "p_43": "view"
  },
  "CTO": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "view",
    "p_7": "view",
    "p_8": "view",
    "p_9": "view",
    "p_10": "view",
    "p_11": "view",
    "p_12": "view",
    "p_13": "view",
    "p_14": "view",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "view",
    "p_20": "view",
    "p_21": "view",
    "p_22": "view",
    "p_23": "view",
    "p_24": "view",
    "p_25": "view",
    "p_26": "view",
    "p_27": "view",
    "p_28": "view",
    "p_29": "view",
    "p_30": "view",
    "p_31": "view",
    "p_32": "view",
    "p_33": "view",
    "p_34": "view",
    "p_35": "view",
    "p_36": "view",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "view",
    "p_40": "view",
    "p_41": "view",
    "p_42": "view",
    "p_43": "view"
  },
  "IT Admin": {
    "p_1": "none",
    "p_2": "none",
    "p_3": "none",
    "p_4": "none",
    "p_5": "none",
    "p_6": "none",
    "p_7": "none",
    "p_8": "none",
    "p_9": "none",
    "p_10": "none",
    "p_11": "none",
    "p_12": "none",
    "p_13": "none",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "none",
    "p_18": "none",
    "p_19": "none",
    "p_20": "none",
    "p_21": "none",
    "p_22": "none",
    "p_23": "none",
    "p_24": "none",
    "p_25": "none",
    "p_26": "none",
    "p_27": "none",
    "p_28": "none",
    "p_29": "view",
    "p_30": "view",
    "p_31": "manage",
    "p_32": "view",
    "p_33": "none",
    "p_34": "none",
    "p_35": "none",
    "p_36": "none",
    "p_37": "none",
    "p_38": "none",
    "p_39": "none",
    "p_40": "none",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Accounts": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "view",
    "p_8": "view",
    "p_9": "view",
    "p_10": "view",
    "p_11": "view",
    "p_12": "view",
    "p_13": "view",
    "p_14": "view",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "view",
    "p_20": "none",
    "p_21": "none",
    "p_22": "none",
    "p_23": "view",
    "p_24": "manage",
    "p_25": "view",
    "p_26": "view",
    "p_27": "manage",
    "p_28": "manage",
    "p_29": "none",
    "p_30": "none",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "view",
    "p_35": "view",
    "p_36": "none",
    "p_37": "none",
    "p_38": "none",
    "p_39": "none",
    "p_40": "none",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "HR": {
    "p_1": "none",
    "p_2": "none",
    "p_3": "none",
    "p_4": "none",
    "p_5": "none",
    "p_6": "none",
    "p_7": "none",
    "p_8": "none",
    "p_9": "none",
    "p_10": "none",
    "p_11": "none",
    "p_12": "none",
    "p_13": "none",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "none",
    "p_18": "none",
    "p_19": "none",
    "p_20": "none",
    "p_21": "none",
    "p_22": "none",
    "p_23": "none",
    "p_24": "none",
    "p_25": "none",
    "p_26": "none",
    "p_27": "none",
    "p_28": "none",
    "p_29": "view",
    "p_30": "view",
    "p_31": "manage",
    "p_32": "manage",
    "p_33": "none",
    "p_34": "none",
    "p_35": "none",
    "p_36": "none",
    "p_37": "none",
    "p_38": "none",
    "p_39": "none",
    "p_40": "none",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Sales Manager": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "manage",
    "p_7": "manage",
    "p_8": "view",
    "p_9": "view",
    "p_10": "view",
    "p_11": "view",
    "p_12": "view",
    "p_13": "view",
    "p_14": "view",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "view",
    "p_20": "none",
    "p_21": "none",
    "p_22": "view",
    "p_23": "manage",
    "p_24": "view",
    "p_25": "manage",
    "p_26": "view",
    "p_27": "view",
    "p_28": "view",
    "p_29": "none",
    "p_30": "view",
    "p_31": "none",
    "p_32": "none",
    "p_33": "manage",
    "p_34": "manage",
    "p_35": "none",
    "p_36": "none",
    "p_37": "none",
    "p_38": "none",
    "p_39": "none",
    "p_40": "none",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Sales Team Member": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "manage",
    "p_7": "view",
    "p_8": "view",
    "p_9": "view",
    "p_10": "view",
    "p_11": "view",
    "p_12": "view",
    "p_13": "view",
    "p_14": "view",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "view",
    "p_20": "none",
    "p_21": "none",
    "p_22": "view",
    "p_23": "manage",
    "p_24": "view",
    "p_25": "manage",
    "p_26": "view",
    "p_27": "view",
    "p_28": "view",
    "p_29": "none",
    "p_30": "view",
    "p_31": "none",
    "p_32": "none",
    "p_33": "manage",
    "p_34": "view",
    "p_35": "none",
    "p_36": "none",
    "p_37": "none",
    "p_38": "none",
    "p_39": "none",
    "p_40": "none",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "PMO": {
    "p_1": "manage",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "manage",
    "p_9": "manage",
    "p_10": "manage",
    "p_11": "manage",
    "p_12": "manage",
    "p_13": "view",
    "p_14": "none",
    "p_15": "manage",
    "p_16": "manage",
    "p_17": "manage",
    "p_18": "manage",
    "p_19": "manage",
    "p_20": "manage",
    "p_21": "view",
    "p_22": "view",
    "p_23": "view",
    "p_24": "none",
    "p_25": "none",
    "p_26": "manage",
    "p_27": "view",
    "p_28": "view",
    "p_29": "view",
    "p_30": "manage",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "view",
    "p_35": "manage",
    "p_36": "view",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "manage",
    "p_40": "manage",
    "p_41": "manage",
    "p_42": "manage",
    "p_43": "manage"
  },
  "EM (Engagement Manager)": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "manage",
    "p_4": "manage",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "manage",
    "p_9": "manage",
    "p_10": "manage",
    "p_11": "manage",
    "p_12": "view",
    "p_13": "view",
    "p_14": "none",
    "p_15": "view",
    "p_16": "view",
    "p_17": "view",
    "p_18": "view",
    "p_19": "manage",
    "p_20": "manage",
    "p_21": "manage",
    "p_22": "manage",
    "p_23": "manage",
    "p_24": "none",
    "p_25": "none",
    "p_26": "view",
    "p_27": "view",
    "p_28": "view",
    "p_29": "view",
    "p_30": "manage",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "view",
    "p_35": "none",
    "p_36": "manage",
    "p_37": "manage",
    "p_38": "manage",
    "p_39": "none",
    "p_40": "none",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  },
  "Intern": {
    "p_1": "view",
    "p_2": "manage",
    "p_3": "view",
    "p_4": "view",
    "p_5": "manage",
    "p_6": "none",
    "p_7": "none",
    "p_8": "none",
    "p_9": "none",
    "p_10": "none",
    "p_11": "none",
    "p_12": "none",
    "p_13": "none",
    "p_14": "none",
    "p_15": "none",
    "p_16": "none",
    "p_17": "none",
    "p_18": "none",
    "p_19": "none",
    "p_20": "none",
    "p_21": "none",
    "p_22": "none",
    "p_23": "none",
    "p_24": "none",
    "p_25": "none",
    "p_26": "none",
    "p_27": "none",
    "p_28": "none",
    "p_29": "none",
    "p_30": "none",
    "p_31": "none",
    "p_32": "none",
    "p_33": "none",
    "p_34": "none",
    "p_35": "none",
    "p_36": "none",
    "p_37": "none",
    "p_38": "none",
    "p_39": "none",
    "p_40": "none",
    "p_41": "none",
    "p_42": "none",
    "p_43": "none"
  }
};

export const BASELINE_STORAGE_KEY = "pulse-rbac-baseline-overrides";

export function mapRoleToExcelRole(role: string): string {
  const r = (role || "").toLowerCase().trim();
  if (r === "admin" || r === "dhanshree") return "CEO";
  if (r === "ceo" || r === "business_owner") return "CEO";
  if (r === "coo") return "COO";
  if (r === "cto") return "CTO";
  if (r === "it admin") return "IT Admin";
  if (r === "accounts" || r === "accounts_finance") return "Accounts";
  if (r === "hr") return "HR";
  if (r === "sales manager") return "Sales Manager";
  if (r === "sales team member" || r === "sales_bd") return "Sales Team Member";
  if (r === "pmo") return "PMO";
  if (r.includes("engagement") || r === "em (engagement manager)") return "EM (Engagement Manager)";
  if (r === "intern") return "Intern";
  if (r.includes("r&d") || r.includes("r and d")) return "Team Member (R&D only)";
  if (r.includes("hod")) return "HOD";
  if (r.includes("senior manager") || r === "senior_pm") return "Senior Manager (Sr. Project Manager)";
  if (r.includes("manager") || r === "pm" || r === "project manager") return "Manager (Project Manager)";
  if (r.includes("leader") || r.includes("lead")) return "Team Lead";
  return "Team Member";
}

export function getBaselineAccessForRole(role: string): Record<string, AccessLevel> {
  const isSuperAdmin = role?.toLowerCase() === "admin" || role?.toLowerCase() === "dhanshree";
  if (isSuperAdmin) {
    const full: Record<string, AccessLevel> = {};
    for (const p of EXCEL_PAGE_DEFINITIONS) full[p.id] = "manage";
    return full;
  }
  const excelRole = mapRoleToExcelRole(role);
  const baseline = EXCEL_ROLE_BASELINES[excelRole];
  if (baseline) return { ...baseline };
  return { ...(EXCEL_ROLE_BASELINES["Team Member"] ?? {}) };
}

export function getRoleCurrentAccess(role: string): Record<string, AccessLevel> {
  const baseline = getBaselineAccessForRole(role);
  if (typeof window === "undefined") return baseline;

  try {
    const raw = localStorage.getItem(BASELINE_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed && parsed[role]) {
        return { ...baseline, ...parsed[role] };
      }
    }
  } catch {
    /* ignore */
  }

  return baseline;
}

export function saveRoleAccess(
  role: string,
  accessMap: Record<string, AccessLevel>,
): void {
  if (typeof window === "undefined") return;
  try {
    const raw = localStorage.getItem(BASELINE_STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : {};
    parsed[role] = accessMap;
    localStorage.setItem(BASELINE_STORAGE_KEY, JSON.stringify(parsed));
    window.dispatchEvent(new Event("pulse-rbac-updated"));
  } catch {
    /* ignore */
  }
}

export function resetRoleToBaseline(role: string): Record<string, AccessLevel> {
  if (typeof window !== "undefined") {
    try {
      const raw = localStorage.getItem(BASELINE_STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        delete parsed[role];
        localStorage.setItem(BASELINE_STORAGE_KEY, JSON.stringify(parsed));
        window.dispatchEvent(new Event("pulse-rbac-updated"));
      }
    } catch {
      /* ignore */
    }
  }
  return getBaselineAccessForRole(role);
}

export function hasCustomOverrides(role: string): boolean {
  if (typeof window === "undefined") return false;
  try {
    const raw = localStorage.getItem(BASELINE_STORAGE_KEY);
    if (!raw) return false;
    const parsed = JSON.parse(raw);
    return Boolean(parsed && parsed[role] && Object.keys(parsed[role]).length > 0);
  } catch {
    return false;
  }
}

export function isPageVisibleForRole(
  role: string,
  pageId: string,
  currentAccess?: Record<string, AccessLevel>,
): boolean {
  if (role?.toLowerCase() === "admin" || role?.toLowerCase() === "dhanshree") return true;
  const access = currentAccess ? currentAccess[pageId] : getRoleCurrentAccess(role)[pageId];
  return access === "manage" || access === "view";
}

