import type { Role } from "@/lib/mock-data";
import { PERMISSION_CATALOG, type PermissionKey } from "./catalog";

const allKeys = PERMISSION_CATALOG.map((p) => p.key) as PermissionKey[];

function keys(...list: PermissionKey[]): PermissionKey[] {
  return list;
}

const EMPLOYEE_PROFILE_LIMITED: PermissionKey[] = [];

const RESOURCES_EMPLOYEE_LIKE = keys(
  "resources.view",
);

const RESOURCES_PM_LIKE = keys(
  "resources.view",
  "resources.pool",
  "resources.columns.full",
  "resources.profile.org",
  "resources.profile.employment",
  "resources.profile.skills",
  "resources.profile.kpi",
  "resources.profile.finance",
);

const PM_CORE = keys(
  "dashboard.view",
  "action.bucket_list",
  "action.bucket_timer",
  "action.approvals",
  "action.alerts",
  "action.notifications",
  "action.acknowledge",
  "projects.view",
  "projects.stage_tracker",
  "projects.tab.overview",
  "projects.tab.wbs",
  "projects.tab.team",
  "projects.tab.tasks",
  "projects.tab.health",
  "projects.overview.edit_tl",
  "projects.overview.view_spm",
  "projects.wbs.services",
  "projects.team.edit",
  "projects.tasks.edit",
  "projects.health.issues",
  "projects.health.alerts",
  "projects.health.appreciation",
  ...RESOURCES_PM_LIKE,
  "customers.view",
  "repository.view",
  "repository.download",
  "timesheet.my",
  "timesheet.approve",
);

const PMO_CORE = keys(
  "dashboard.view",
  "action.approvals",
  "action.alerts",
  "action.notifications",
  "action.acknowledge",
  "projects.view",
  "projects.stage_tracker",
  "projects.tab.overview",
  "projects.tab.wbs",
  "projects.tab.team",
  "projects.tab.tasks",
  "projects.tab.health",
  "projects.tab.invoices",
  "projects.overview.view_spm",
  "projects.wbs.pmo_intake",
  "projects.wbs.services",
  "projects.wbs.project_allocation",
  "projects.wbs.service_prereq",
  "projects.health.issues",
  "projects.health.alerts",
  "projects.health.appreciation",
  "projects.invoices.limited",
  "reports.sales",
  "reports.wbs_tracker",
  "reports.po_tracker",
  "reports.invoice_tracker",
  ...RESOURCES_PM_LIKE,
  "customers.view",
  "customers.create",
  "customers.change_em",
  "repository.view",
  "repository.download",
  "repository.upload",
  "repository.delete",
  "repository.logs",
  "my_team.dashboard",
);

const BO_VIEW = PMO_CORE.filter(
  (k) =>
    k !== "action.acknowledge" &&
    k !== "repository.upload" &&
    k !== "repository.delete" &&
    k !== "repository.logs" &&
    k !== "customers.create" &&
    k !== "customers.change_em",
);

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, PermissionKey[]> = {
  // 27 discrete roles
  CEO: allKeys,
  COO: keys(
    "dashboard.view",
    "action.approvals",
    "action.alerts",
    "action.notifications",
    "action.acknowledge",
    "projects.view",
    "projects.stage_tracker",
    "projects.tab.overview",
    "projects.tab.wbs",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "projects.tab.invoices",
    "projects.overview.budget",
    "projects.overview.view_spm",
    "projects.wbs.services",
    "projects.health.issues",
    "projects.health.alerts",
    "reports.sales",
    "reports.wbs_tracker",
    "reports.po_tracker",
    "reports.invoice_tracker",
    ...RESOURCES_PM_LIKE,
    "customers.view",
    "repository.view",
    "repository.download",
    "my_team.dashboard",
  ),
  CTO: keys(
    "dashboard.view",
    "action.alerts",
    "action.notifications",
    "projects.view",
    "projects.stage_tracker",
    "projects.tab.overview",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "reports.wbs_tracker",
    ...RESOURCES_PM_LIKE,
    "repository.view",
    "repository.download",
    "repository.upload",
    "my_team.dashboard",
  ),
  "IT Admin": keys(
    "dashboard.view",
    "resources.view",
    "resources.pool",
    "resources.add_employee",
    "resources.columns.full",
    "resources.profile.org",
    "resources.profile.employment",
    "resources.profile.skills",
    "resources.profile.kpi",
    "resources.profile.finance",
    "resources.profile.edit",
    "resources.profile.offboard",
    "resources.exit_summary",
    "repository.view",
    "repository.download",
    "repository.upload",
    "settings.view",
  ),
  Accounts: keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.overview",
    "projects.tab.wbs",
    "projects.tab.invoices",
    "projects.overview.budget",
    "projects.overview.view_spm",
    "projects.wbs.services",
    "projects.wbs.amount",
    "projects.invoices.edit",
    "projects.invoices.amount",
    "reports.po_tracker",
    "reports.invoice_tracker",
    "resources.view",
    "customers.view",
    "customers.create",
    "customers.change_em",
    "repository.view",
    "repository.download",
  ),
  HR: keys(
    "dashboard.view",
    "resources.view",
    "resources.pool",
    "resources.add_employee",
    "resources.columns.full",
    "resources.profile.org",
    "resources.profile.employment",
    "resources.profile.skills",
    "resources.profile.kpi",
    "resources.profile.finance",
    "resources.profile.edit",
    "resources.profile.offboard",
    "resources.exit_summary",
    "repository.view",
    "repository.download",
    "repository.upload",
    "repository.delete",
    "repository.logs",
    "settings.view",
  ),
  "Sales Manager": keys(
    "dashboard.view",
    "action.alerts",
    "action.notifications",
    "projects.view",
    "projects.create",
    "projects.drafts",
    "projects.stage_tracker",
    "projects.tab.overview",
    "projects.tab.wbs",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "projects.tab.invoices",
    "projects.overview.budget",
    "projects.overview.view_spm",
    "projects.wbs.pmo_intake",
    "projects.wbs.services",
    "projects.wbs.amount",
    "projects.health.issues",
    "projects.health.alerts",
    "projects.health.appreciation",
    "projects.invoices.amount",
    "reports.sales",
    "reports.wbs_tracker",
    "resources.view",
    "customers.view",
    "customers.create",
    "customers.change_em",
    "repository.view",
    "repository.download",
    "my_team.dashboard",
    "timesheet.my",
  ),
  "Sales team member": keys(
    "dashboard.view",
    "projects.view",
    "projects.overview.view_spm",
    "reports.sales",
    "customers.view",
    "customers.create",
    "repository.view",
    "repository.download",
    "my_team.dashboard",
    "timesheet.my",
  ),
  PMO: PMO_CORE,
  EngagementManager: keys(
    ...PM_CORE.filter((k) => k !== "projects.overview.edit_tl"),
    "projects.health.customer_engagement",
  ),
  Intern: keys(
    "projects.view",
    "projects.tab.tasks",
    "repository.view",
    "repository.download",
    "timesheet.my",
    "my_team.dashboard",
  ),
  "Testing HOD": keys(
    ...BO_VIEW,
    "action.acknowledge",
  ),
  "Testing Senior Manager": keys(
    ...PM_CORE,
    "projects.overview.edit_pm",
  ),
  "Testing-Manager": PM_CORE,
  "Testing-Team Leader": keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tasks.edit",
    "projects.tab.health",
    "projects.health.issues",
    "resources.view",
    "repository.view",
    "repository.download",
    "timesheet.my",
    "timesheet.approve",
    "my_team.dashboard",
  ),
  "Testing-Team Member": keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "projects.health.issues",
    "resources.view",
    "repository.view",
    "repository.download",
    "timesheet.my",
    "my_team.dashboard",
  ),
  "Consulting-HOD": keys(
    ...BO_VIEW,
    "action.acknowledge",
  ),
  "Consulting-Senior Manager": keys(
    ...PM_CORE,
    "projects.overview.edit_pm",
  ),
  "Consulting-Manager": PM_CORE,
  "Consulting-Team Leader": keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tasks.edit",
    "projects.tab.health",
    "projects.health.issues",
    "resources.view",
    "repository.view",
    "repository.download",
    "timesheet.my",
    "timesheet.approve",
    "my_team.dashboard",
  ),
  "Consulting-Team member": keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "projects.health.issues",
    "resources.view",
    "repository.view",
    "repository.download",
    "timesheet.my",
    "my_team.dashboard",
  ),
  "SOC-HOD": keys(
    ...BO_VIEW,
    "action.acknowledge",
  ),
  "SOC-Senior Manager": keys(
    ...PM_CORE,
    "projects.overview.edit_pm",
  ),
  "SOC-Manager": PM_CORE,
  "SOC-Team Leader": keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tasks.edit",
    "projects.tab.health",
    "projects.health.issues",
    "resources.view",
    "repository.view",
    "repository.download",
    "timesheet.my",
    "timesheet.approve",
    "my_team.dashboard",
  ),
  "SOC-Team Member": keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "projects.health.issues",
    "resources.view",
    "repository.view",
    "repository.download",
    "timesheet.my",
    "my_team.dashboard",
  ),
  "R&D - Team member": keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "repository.view",
    "repository.download",
    "repository.upload",
    "timesheet.my",
    "my_team.dashboard",
  ),

  // Legacy system roles
  employee: keys(
    "dashboard.view",
    "action.bucket_list",
    "action.bucket_timer",
    "action.notifications",
    "projects.view",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "projects.health.issues",
    "projects.health.alerts",
    "projects.health.appreciation",
    "resources.view",
    "repository.view",
    "repository.download",
    "timesheet.my",
    ...EMPLOYEE_PROFILE_LIMITED,
  ),
  pm: PM_CORE,
  senior_pm: keys(
    ...PM_CORE,
    "projects.overview.edit_pm",
  ),
  engagement_manager: keys(
    ...PM_CORE.filter((k) => k !== "projects.overview.edit_tl"),
    "projects.health.customer_engagement",
  ),
  pmo: PMO_CORE,
  business_owner: BO_VIEW,
  hod: keys(
    ...BO_VIEW,
    "action.acknowledge",
  ),
  hr: keys(
    "dashboard.view",
    "resources.view",
    "resources.profile.org",
    "resources.profile.employment",
    "resources.profile.skills",
    "resources.profile.kpi",
    "resources.profile.finance",
    "repository.view",
    "repository.download",
    "repository.upload",
    "repository.delete",
    "repository.logs",
  ),
  accounts_finance: keys(
    "dashboard.view",
    "projects.view",
    "projects.tab.overview",
    "projects.tab.wbs",
    "projects.tab.invoices",
    "projects.overview.budget",
    "projects.overview.view_spm",
    "projects.wbs.services",
    "projects.wbs.amount",
    "projects.invoices.edit",
    "projects.invoices.amount",
    "reports.po_tracker",
    "reports.invoice_tracker",
    "resources.view",
    "customers.view",
    "customers.create",
    "customers.change_em",
    "repository.view",
    "repository.download",
  ),
  sales_bd: keys(
    "dashboard.view",
    "action.alerts",
    "action.notifications",
    "projects.view",
    "projects.create",
    "projects.drafts",
    "projects.stage_tracker",
    "projects.tab.overview",
    "projects.tab.wbs",
    "projects.tab.team",
    "projects.tab.tasks",
    "projects.tab.health",
    "projects.tab.invoices",
    "projects.overview.budget",
    "projects.overview.view_spm",
    "projects.wbs.pmo_intake",
    "projects.wbs.services",
    "projects.wbs.amount",
    "projects.health.issues",
    "projects.health.alerts",
    "projects.health.appreciation",
    "projects.invoices.amount",
    "reports.sales",
    "reports.wbs_tracker",
    "resources.view",
    "customers.view",
    "customers.create",
    "repository.view",
    "repository.download",
  ),
  dhanshree: allKeys,
};

export const RBAC_STORAGE_KEY = "pulse-rbac-overrides";
