import type { Role } from "@/lib/mock-data";
import { PERMISSION_CATALOG, type PermissionKey } from "./catalog";

const allKeys = PERMISSION_CATALOG.map((p) => p.key) as PermissionKey[];

function keys(...list: PermissionKey[]): PermissionKey[] {
  return Array.from(new Set(list));
}

const RESOURCES_ALL = keys(
  "resources.view",
  "resources.directory.view",
  "resources.pool",
  "resources.pool.view",
  "resources.columns.full",
  "resources.profile.org",
  "resources.profile.employment",
  "resources.profile.skills",
  "resources.profile.kpi",
  "resources.profile.finance",
  "resources.exit_summary",
  "resources.exit-summary.view",
);

const PM_CORE = keys(
  "dashboard.view",
  "dashboard.stats",
  "dashboard.kpi",
  "dashboard.activity",
  "action-center.view",
  "action.bucket_list",
  "action-center.bucket-list.view",
  "action.bucket_timer",
  "action-center.bucket-list.timer",
  "action.approvals",
  "action-center.approvals.view",
  "action.acknowledge",
  "action-center.approvals.act",
  "action.alerts",
  "action-center.alerts.view",
  "action-center.alerts.resolve",
  "action.notifications",
  "action-center.notifications.view",
  "projects.view",
  "projects.stage_tracker",
  "projects.stage-tracker.view",
  "projects.stage-tracker.edit",
  "projects.tab.overview",
  "projects.overview.view",
  "projects.overview.edit",
  "projects.overview.budget",
  "projects.budget.view",
  "projects.overview.edit_tl",
  "projects.overview.view_spm",
  "projects.tab.wbs",
  "projects.wbs.view",
  "projects.wbs.services",
  "projects.tab.team",
  "projects.team.view",
  "projects.team.edit",
  "projects.team.assign",
  "projects.tab.tasks",
  "projects.task.view",
  "projects.task.create",
  "projects.tasks.edit",
  "projects.task.assign",
  "projects.task.update-status",
  "projects.tab.health",
  "projects.health.view",
  "projects.health.issues",
  "projects.health.raise-issue",
  "projects.health.edit-issue",
  "projects.health.resolve-issue",
  "projects.health.alerts",
  "projects.health.appreciation",
  ...RESOURCES_ALL,
  "customers.view",
  "repository.view",
  "repository.download",
  "my-team.dashboard.view",
  "my_team.dashboard",
  "timesheet.my",
  "my-team.my-timesheet.view",
  "my-team.my-timesheet.submit",
  "my-team.my-timesheet.edit",
  "timesheet.approve",
  "my-team.timesheet-approval.view",
  "my-team.timesheet-approval.approve",
  "my-team.timesheet-approval.reject",
);

const PMO_CORE = keys(
  "dashboard.view",
  "dashboard.stats",
  "dashboard.kpi",
  "dashboard.activity",
  "action-center.view",
  "action.approvals",
  "action-center.approvals.view",
  "action.acknowledge",
  "action-center.approvals.act",
  "action.alerts",
  "action-center.alerts.view",
  "action-center.alerts.resolve",
  "action.notifications",
  "action-center.notifications.view",
  "projects.view",
  "projects.stage_tracker",
  "projects.stage-tracker.view",
  "projects.tab.overview",
  "projects.overview.view",
  "projects.overview.view_spm",
  "projects.tab.wbs",
  "projects.wbs.view",
  "projects.wbs.pmo_intake",
  "projects.wbs.services",
  "projects.wbs.project_allocation",
  "projects.wbs.service_prereq",
  "projects.tab.team",
  "projects.team.view",
  "projects.tab.tasks",
  "projects.task.view",
  "projects.tab.health",
  "projects.health.view",
  "projects.health.issues",
  "projects.health.alerts",
  "projects.health.appreciation",
  "projects.tab.invoices",
  "projects.invoices.view",
  "projects.invoices.limited",
  "reports.view",
  "reports.sales",
  "reports.wbs_tracker",
  "reports.po_tracker",
  "reports.invoice_tracker",
  "reports.export",
  ...RESOURCES_ALL,
  "customers.view",
  "customers.create",
  "customers.change_em",
  "repository.view",
  "repository.download",
  "repository.upload",
  "repository.delete",
  "repository.logs",
  "my-team.dashboard.view",
  "my_team.dashboard",
);

const BO_VIEW = PMO_CORE.filter(
  (k) =>
    k !== "action.acknowledge" &&
    k !== "action-center.approvals.act" &&
    k !== "repository.upload" &&
    k !== "repository.delete" &&
    k !== "repository.logs" &&
    k !== "customers.create" &&
    k !== "customers.change_em",
);

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, PermissionKey[]> = {
  employee: keys(
    "dashboard.view",
    "dashboard.stats",
    "dashboard.activity",
    "action-center.view",
    "action.bucket_list",
    "action-center.bucket-list.view",
    "action.bucket_timer",
    "action-center.bucket-list.timer",
    "action.notifications",
    "action-center.notifications.view",
    "projects.view",
    "projects.tab.team",
    "projects.team.view",
    "projects.tab.tasks",
    "projects.task.view",
    "projects.task.update-status",
    "projects.tab.health",
    "projects.health.view",
    "projects.health.issues",
    "projects.health.alerts",
    "projects.health.appreciation",
    "resources.view",
    "resources.directory.view",
    "repository.view",
    "repository.download",
    "my-team.dashboard.view",
    "my_team.dashboard",
    "timesheet.my",
    "my-team.my-timesheet.view",
    "my-team.my-timesheet.submit",
    "my-team.my-timesheet.edit",
  ),

  pm: PM_CORE,

  senior_pm: keys(
    ...PM_CORE,
    "projects.overview.edit_pm",
    "projects.overview.edit_spm",
  ),

  engagement_manager: keys(
    ...PM_CORE.filter((k) => k !== "projects.overview.edit_tl"),
    "projects.health.customer_engagement",
  ),

  pmo: PMO_CORE,

  business_owner: BO_VIEW,

  hod: keys(
    ...BO_VIEW,
    "action.acknowledge",
    "action-center.approvals.act",
  ),

  hr: keys(
    "dashboard.view",
    "resources.view",
    "resources.directory.view",
    "resources.add_employee",
    "resources.directory.add-employee",
    "resources.columns.full",
    "resources.profile.org",
    "resources.profile.employment",
    "resources.profile.skills",
    "resources.profile.kpi",
    "resources.profile.finance",
    "resources.profile.edit",
    "resources.profile.report",
    "resources.profile.offboard",
    "resources.exit_summary",
    "resources.exit-summary.view",
    "repository.view",
    "repository.download",
    "repository.upload",
    "repository.delete",
    "repository.logs",
  ),

  accounts_finance: keys(
    "dashboard.view",
    "dashboard.stats",
    "projects.view",
    "projects.tab.overview",
    "projects.overview.view",
    "projects.tab.wbs",
    "projects.wbs.view",
    "projects.tab.invoices",
    "projects.invoices.view",
    "projects.overview.budget",
    "projects.budget.view",
    "projects.overview.view_spm",
    "projects.wbs.services",
    "projects.wbs.amount",
    "projects.invoices.edit",
    "projects.invoices.amount",
    "reports.view",
    "reports.po_tracker",
    "reports.invoice_tracker",
    "reports.finance",
    "resources.view",
    "resources.directory.view",
    "customers.view",
    "customers.create",
    "customers.change_em",
    "repository.view",
    "repository.download",
  ),

  sales_bd: keys(
    "dashboard.view",
    "dashboard.stats",
    "action-center.view",
    "action.alerts",
    "action-center.alerts.view",
    "action.notifications",
    "action-center.notifications.view",
    "projects.view",
    "projects.create",
    "projects.drafts",
    "projects.stage_tracker",
    "projects.stage-tracker.view",
    "projects.tab.overview",
    "projects.overview.view",
    "projects.tab.wbs",
    "projects.wbs.view",
    "projects.tab.team",
    "projects.team.view",
    "projects.tab.tasks",
    "projects.task.view",
    "projects.tab.health",
    "projects.health.view",
    "projects.tab.invoices",
    "projects.invoices.view",
    "projects.overview.budget",
    "projects.budget.view",
    "projects.overview.view_spm",
    "projects.wbs.pmo_intake",
    "projects.wbs.services",
    "projects.wbs.amount",
    "projects.health.issues",
    "projects.health.alerts",
    "projects.health.appreciation",
    "projects.invoices.amount",
    "reports.view",
    "reports.sales",
    "reports.wbs_tracker",
    "resources.view",
    "resources.directory.view",
    "customers.view",
    "customers.create",
    "customers.edit",
    "repository.view",
    "repository.download",
  ),

  dhanshree: allKeys,
};

export const RBAC_STORAGE_KEY = "pulse-rbac-overrides";
