namespace PMS.API.Shared.Constants;

/// <summary>
/// Baseline permission sets for every system role, derived from the RBAC
/// master catalog & integration guide (27 roles + legacy roles + super-admins).
/// Used by the seeder (new roles) and by the Settings "Reset Baseline" action.
/// </summary>
public static class RoleBaselines
{
    public static IReadOnlyList<string> For(string roleKey) =>
        Map.TryGetValue(roleKey, out var keys) ? keys : [];

    /// <summary>True when the role key has a known baseline.</summary>
    public static bool HasBaseline(string roleKey) => Map.ContainsKey(roleKey);

    private static readonly Dictionary<string, string[]> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        // ====================================================================
        // Super Admins & Executive Core
        // ====================================================================
        ["Admin"] = AllKeys(),
        ["Dhanshree"] = AllKeys(),
        ["CEO"] = AllKeys(),

        ["COO"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.budget.view",
            "projects.health.view",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "reports.view",
            "reports.export",
            "reports.finance.view",
            "reports.sales",
            "reports.wbs-tracker",
            "reports.po-tracker",
            "reports.invoice-tracker",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "customers.approve",
            "repository.view",
            "repository.download",
            "my-team.dashboard.view",
            "approvals.view",
            "approvals.approve",
            "approvals.reject",
            "wbs.view",
            "portfolio.view",
            Permissions.ClientsRead,
            Permissions.ClientsApprove,
            Permissions.ProjectsRead,
            Permissions.ProjectsClose,
            Permissions.IssuesManage,
            Permissions.ReportsRead,
            Permissions.ResourcesRead,
            Permissions.ApprovalsManage,
        ],

        ["CTO"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.health.view",
            "reports.view",
            "reports.export",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "repository.view",
            "repository.upload",
            "repository.download",
            "my-team.dashboard.view",
            "portfolio.view",
            Permissions.ProjectsRead,
            Permissions.ReportsRead,
            Permissions.ResourcesRead,
        ],

        // ====================================================================
        // Functional Support Roles
        // ====================================================================
        ["IT Admin"] =
        [
            "dashboard.view",
            "resources.view",
            "resources.directory.view",
            "resources.manage",
            "settings.view",
            "settings.masters.manage",
            "repository.view",
            "repository.upload",
            "repository.download",
            Permissions.ResourcesRead,
            Permissions.ResourcesManage,
        ],

        ["Accounts"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.overview.view",
            "projects.health.view",
            "projects.invoice-schedule.view",
            "projects.invoice-schedule.manage",
            "reports.view",
            "reports.export",
            "reports.finance.view",
            "reports.po-tracker",
            "reports.invoice-tracker",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "repository.view",
            Permissions.ClientsRead,
            Permissions.InvoicesRaise,
            Permissions.InvoicesPayment,
            Permissions.ReportsRead,
        ],

        ["HR"] =
        [
            "resources.view",
            "resources.directory.view",
            "resources.manage",
            "resources.kpi.view",
            "resources.profile.org",
            "resources.profile.employment",
            "resources.profile.skills",
            "resources.profile.finance",
            "repository.view",
            "repository.upload",
            "repository.download",
            "settings.view",
            "settings.masters.manage",
            Permissions.ResourcesRead,
            Permissions.ResourcesManage,
        ],
        ["Hr"] =
        [
            "resources.view",
            "resources.directory.view",
            "resources.manage",
            "resources.kpi.view",
            "repository.view",
            Permissions.ResourcesRead,
            Permissions.ResourcesManage,
        ],

        ["Sales Manager"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.create",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.health.view",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "customers.create",
            "customers.edit",
            "customers.assign",
            "customers.approve",
            "reports.view",
            "reports.export",
            "reports.sales",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            Permissions.ClientsRead,
            Permissions.ClientsWrite,
            Permissions.ClientsApprove,
            Permissions.ProjectsWrite,
            Permissions.WbsRead,
            Permissions.TimesheetsSubmit,
        ],

        ["Sales team member"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.overview.view",
            "customers.view",
            "customers.create",
            "customers.edit",
            "reports.view",
            "reports.sales",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            Permissions.ClientsRead,
            Permissions.ClientsWrite,
            Permissions.TimesheetsSubmit,
        ],
        ["Sales"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.create",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.health.view",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "customers.create",
            "customers.edit",
            "customers.assign",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            Permissions.ClientsWrite,
            Permissions.ProjectsWrite,
            Permissions.WbsRead,
            Permissions.TimesheetsSubmit,
        ],

        ["PMO"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.budget.view",
            "projects.pmo.view",
            "projects.pmo.manage",
            "projects.health.view",
            "projects.health.manage",
            "reports.view",
            "reports.export",
            "reports.wbs-tracker",
            "resources.view",
            "resources.directory.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "approvals.view",
            "wbs.view",
            "wbs.allocate",
            Permissions.ClientsRead,
            Permissions.ProjectsRead,
            Permissions.WbsRead,
            Permissions.WbsAllocate,
            Permissions.TimesheetsMonitor,
            Permissions.IssuesManage,
            Permissions.ResourcesRead,
            Permissions.ReportsRead,
            Permissions.ApprovalsManage,
        ],
        ["Pmo"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.budget.view",
            "reports.view",
            "reports.export",
            "resources.view",
            "resources.directory.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "approvals.view",
            "wbs.view",
            "wbs.allocate",
            Permissions.ClientsRead,
            Permissions.ProjectsRead,
            Permissions.WbsRead,
            Permissions.WbsAllocate,
            Permissions.TimesheetsMonitor,
            Permissions.IssuesManage,
            Permissions.ResourcesRead,
            Permissions.ReportsRead,
            Permissions.ApprovalsManage,
        ],

        // ====================================================================
        // Project Delivery & Internship
        // ====================================================================
        ["EngagementManager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.budget.view",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "projects.health-issues.edit",
            "projects.health-issues.resolve",
            "projects.alerts.view",
            "projects.alerts.create",
            "projects.alerts.resolve",
            "projects.escalation.view",
            "projects.escalation.create",
            "projects.escalation.resolve",
            "projects.communication.view",
            "projects.communication.create",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "customers.edit",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            Permissions.ClientsRead,
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
        ],

        ["SeniorPm"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.budget.view",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "projects.health-issues.edit",
            "projects.health-issues.resolve",
            "projects.alerts.view",
            "projects.alerts.create",
            "projects.alerts.resolve",
            "projects.escalation.view",
            "projects.escalation.create",
            "projects.escalation.resolve",
            "projects.communication.view",
            "projects.communication.create",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            Permissions.ClientsRead,
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.ProjectsClose,
            Permissions.IssuesRaise,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
        ],

        ["ProjectManager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.budget.view",
            "projects.team.view",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "projects.health-issues.edit",
            "projects.health-issues.resolve",
            "projects.alerts.view",
            "projects.alerts.create",
            "projects.alerts.resolve",
            "projects.escalation.view",
            "projects.escalation.create",
            "projects.escalation.resolve",
            "projects.communication.view",
            "projects.communication.create",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
            Permissions.TimesheetsApprove,
        ],

        ["Intern"] =
        [
            "projects.view",
            "projects.assigned-projects.view",
            "projects.task.view",
            "projects.task.update-status",
            "repository.view",
            "repository.download",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            Permissions.TimesheetsSubmit,
        ],

        ["Employee"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.assigned-projects.view",
            "projects.task.view",
            "projects.task.update-status",
            "resources.view",
            "resources.directory.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.TimesheetsSubmit,
            Permissions.IssuesRaise,
        ],

        ["TeamLead"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.task.view",
            "projects.task.update-status",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
        ],

        ["BusinessOwner"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.health.view",
            "projects.health-issues.view",
            "reports.view",
            "reports.export",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "portfolio.view",
            Permissions.ClientsRead,
            Permissions.ProjectsRead,
            Permissions.ReportsRead,
        ],

        ["Hod"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.health.view",
            "projects.health.manage",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "reports.view",
            "reports.export",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "customers.approve",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "approvals.view",
            "approvals.approve",
            "approvals.reject",
            Permissions.ClientsRead,
            Permissions.ClientsApprove,
            Permissions.ProjectsRead,
            Permissions.ProjectsClose,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
            Permissions.ApprovalsManage,
            Permissions.ReportsRead,
        ],

        // ====================================================================
        // Departmental Services: Testing
        // ====================================================================
        ["Testing HOD"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.health.view",
            "projects.health.manage",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "reports.view",
            "reports.export",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "approvals.view",
            "approvals.approve",
            "approvals.reject",
            Permissions.ProjectsRead,
            Permissions.ProjectsClose,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
            Permissions.ApprovalsManage,
            Permissions.ReportsRead,
        ],

        ["Testing Senior Manager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.budget.view",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "resources.view",
            "resources.directory.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
        ],

        ["Testing-Manager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "projects.health-issues.edit",
            "projects.health-issues.resolve",
            "projects.alerts.view",
            "projects.alerts.create",
            "projects.alerts.resolve",
            "projects.escalation.view",
            "projects.escalation.create",
            "projects.escalation.resolve",
            "resources.view",
            "resources.directory.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
            Permissions.TimesheetsApprove,
        ],

        ["Testing-Team Leader"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.overview.view",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.ProjectsRead,
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
            Permissions.TimesheetsApprove,
        ],

        ["Testing-Team Member"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.assigned-projects.view",
            "projects.task.view",
            "projects.task.update-status",
            "projects.health.raise-issue",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
        ],

        // ====================================================================
        // Departmental Services: Consulting
        // ====================================================================
        ["Consulting-HOD"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.health.view",
            "projects.health.manage",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "reports.view",
            "reports.export",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "approvals.view",
            "approvals.approve",
            "approvals.reject",
            Permissions.ProjectsRead,
            Permissions.ProjectsClose,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
            Permissions.ApprovalsManage,
            Permissions.ReportsRead,
        ],

        ["Consulting-Senior Manager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.budget.view",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "resources.view",
            "resources.directory.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
        ],

        ["Consulting-Manager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "projects.health-issues.edit",
            "projects.health-issues.resolve",
            "projects.alerts.view",
            "projects.alerts.create",
            "projects.alerts.resolve",
            "projects.escalation.view",
            "projects.escalation.create",
            "projects.escalation.resolve",
            "resources.view",
            "resources.directory.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
            Permissions.TimesheetsApprove,
        ],

        ["Consulting-Team Leader"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.overview.view",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.ProjectsRead,
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
            Permissions.TimesheetsApprove,
        ],

        ["Consulting-Team member"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.assigned-projects.view",
            "projects.task.view",
            "projects.task.update-status",
            "projects.health.raise-issue",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
        ],

        // ====================================================================
        // Departmental Services: Operations (SOC)
        // ====================================================================
        ["SOC-HOD"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.health.view",
            "projects.health.manage",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "reports.view",
            "reports.export",
            "resources.view",
            "resources.directory.view",
            "resources.kpi.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "approvals.view",
            "approvals.approve",
            "approvals.reject",
            Permissions.ProjectsRead,
            Permissions.ProjectsClose,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
            Permissions.ApprovalsManage,
            Permissions.ReportsRead,
        ],

        ["SOC-Senior Manager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.budget.view",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.alerts.view",
            "projects.escalation.view",
            "resources.view",
            "resources.directory.view",
            "customers.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.IssuesManage,
            Permissions.TimesheetsApprove,
        ],

        ["SOC-Manager"] =
        [
            "dashboard.view",
            "action-center.view",
            "projects.view",
            "projects.overview.view",
            "projects.overview.edit",
            "projects.team.view",
            "projects.team.assign",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.edit-issue",
            "projects.health.resolve-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "projects.health-issues.edit",
            "projects.health-issues.resolve",
            "projects.alerts.view",
            "projects.alerts.create",
            "projects.alerts.resolve",
            "projects.escalation.view",
            "projects.escalation.create",
            "projects.escalation.resolve",
            "resources.view",
            "resources.directory.view",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.timesheet-approval.reject",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.ProjectsRead,
            Permissions.ProjectsWrite,
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
            Permissions.TimesheetsApprove,
        ],

        ["SOC-Team Leader"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.overview.view",
            "projects.task.view",
            "projects.task.create",
            "projects.task.edit",
            "projects.task.assign",
            "projects.task.update-status",
            "projects.health.view",
            "projects.health.raise-issue",
            "projects.health.comment",
            "projects.health-issues.view",
            "projects.health-issues.create",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.timesheet-approval.view",
            "my-team.timesheet-approval.approve",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.ProjectsRead,
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
            Permissions.TimesheetsApprove,
        ],

        ["SOC-Team Member"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.assigned-projects.view",
            "projects.task.view",
            "projects.task.update-status",
            "projects.health.raise-issue",
            "repository.view",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
        ],

        // ====================================================================
        // R&D (Engineering)
        // ====================================================================
        ["R&D - Team member"] =
        [
            "dashboard.view",
            "projects.view",
            "projects.assigned-projects.view",
            "projects.task.view",
            "projects.task.update-status",
            "repository.view",
            "repository.upload",
            "repository.download",
            "my-team.dashboard.view",
            "my-team.my-timesheet.view",
            "my-team.my-timesheet.submit",
            "my-team.my-timesheet.edit",
            Permissions.IssuesRaise,
            Permissions.TimesheetsSubmit,
        ],
    };

    private static string[] AllKeys() => [.. PermissionCatalog.AllKeys()];
}
