namespace PMS.API.Modules.Projects.DTOs;

public sealed record ProjectDto(
    Guid Id,
    string ProjectCode,
    string? WbsId,
    string Name,
    string? Description,
    Guid ClientId,
    string ClientName,
    string? ClientLogo,
    Guid? SubVentureId,
    string? SubVentureName,
    string Status,
    string Health,
    int Progress,
    string? ContractType,
    string? ProjectType,
    string Currency,
    decimal TaxPercent,
    DateOnly? StartDate,
    DateOnly? EndDate,
    decimal? Budget,
    decimal Spent,
    decimal? TotalHours,
    decimal? TotalDays,
    decimal? InvoiceValue,
    Guid? ProjectManagerId,
    string? ProjectManagerName,
    Guid? TeamLeadId,
    string? TeamLeadName,
    string? EngagementManager,
    Guid? EngagementManagerId,
    string? SalesPerson,
    Guid? SalesPersonId,
    DateOnly? ProjectIssuedDate,
    string? SectionAComments,
    string? SectionBComments,
    string WbsStatus,
    string? WbsSubStatus,
    Guid? RenewedFromProjectId,
    string? RenewedFromWbsId,
    string? PoStatus,
    string? PoNumber,
    DateOnly? PoDate,
    string? BillingModel,
    string? PaymentTerms,
    DateOnly? TargetDate,
    string? AccountContactName,
    string? AccountContactPhone,
    string? AccountContactEmail,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc);

public sealed record CreateProjectRequest(
    Guid ClientId,
    Guid? SubVentureId = null,
    string? Name = null,
    string? Description = null,
    string? Status = "ongoing",
    string? Health = "green",
    string? ContractType = null,
    string? ProjectType = null,
    string? Currency = "INR",
    decimal? TaxPercent = 18m,
    DateOnly? StartDate = null,
    DateOnly? EndDate = null,
    decimal? Budget = null,
    decimal? TotalHours = null,
    decimal? TotalDays = null,
    decimal? InvoiceValue = null,
    Guid? ProjectManagerId = null,
    Guid? TeamLeadId = null,
    string? EngagementManager = null,
    Guid? EngagementManagerId = null,
    string? SalesPerson = null,
    Guid? SalesPersonId = null,
    DateOnly? ProjectIssuedDate = null,
    string? SectionAComments = null,
    string? SectionBComments = null,
    string? WbsStatus = "draft",
    string? WbsSubStatus = null,
    Guid? RenewedFromProjectId = null,
    string? RenewedFromWbsId = null,
    string? PoStatus = null,
    string? PoNumber = null,
    DateOnly? PoDate = null,
    string? BillingModel = null,
    string? PaymentTerms = null,
    DateOnly? TargetDate = null,
    string? AccountContactName = null,
    string? AccountContactPhone = null,
    string? AccountContactEmail = null,
    IReadOnlyList<string>? SubDepartmentNames = null,
    string? ProjectCode = null,
    string? WbsId = null);

public sealed record UpdateProjectRequest(
    string Name,
    string? Description = null,
    string? Status = null,
    string? Health = null,
    int? Progress = null,
    string? ContractType = null,
    string? ProjectType = null,
    string? Currency = null,
    decimal? TaxPercent = null,
    DateOnly? StartDate = null,
    DateOnly? EndDate = null,
    decimal? Budget = null,
    decimal? Spent = null,
    decimal? TotalHours = null,
    decimal? TotalDays = null,
    decimal? InvoiceValue = null,
    Guid? ProjectManagerId = null,
    Guid? TeamLeadId = null,
    string? EngagementManager = null,
    Guid? EngagementManagerId = null,
    string? SalesPerson = null,
    Guid? SalesPersonId = null,
    DateOnly? ProjectIssuedDate = null,
    string? SectionAComments = null,
    string? SectionBComments = null,
    string? WbsStatus = null,
    string? WbsSubStatus = null,
    string? PoStatus = null,
    string? PoNumber = null,
    DateOnly? PoDate = null,
    string? BillingModel = null,
    string? PaymentTerms = null,
    DateOnly? TargetDate = null,
    string? AccountContactName = null,
    string? AccountContactPhone = null,
    string? AccountContactEmail = null);

public sealed record UpdateProjectStatusRequest(string Status);

public sealed record UpdateWbsStatusRequest(string WbsStatus, string? WbsSubStatus = null);

public sealed record NextProjectCodeDto(
    string ProjectSeqId,
    string WbsId,
    string FinancialYear,
    int ClientProjectCount,
    string FormattedClientProjectCount);

public sealed class ProjectQueryParameters
{
    public Guid? ClientId { get; set; }
    public string? Status { get; set; }
    public string? WbsStatus { get; set; }
    public string? Search { get; set; }
    public int Page { get; set; } = 1;
    public int PageSize { get; set; } = 20;
    public int? PerPage { get => PageSize; set { if (value.HasValue) PageSize = value.Value; } }
}
