namespace PMS.API.Modules.Projects.DTOs;

public sealed record ProjectTaskDto(
    Guid Id,
    Guid ProjectId,
    Guid? ProjectServiceId,
    string? ServiceName,
    string Title,
    string? Description,
    string? Period,
    string? Phase,
    string Stage,
    string Priority,
    DateOnly? PlannedStartDate,
    DateOnly? PlannedEndDate,
    DateOnly? ActualStartDate,
    DateOnly? ActualEndDate,
    decimal? EstimatedHours,
    decimal UtilizedHours,
    int Progress,
    int SortOrder,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc);

public sealed record CreateProjectTaskRequest(
    string Title,
    Guid? ProjectServiceId = null,
    string? Description = null,
    string? Period = null,
    string? Phase = null,
    string? Stage = "Ready to Start",
    string? Priority = "medium",
    DateOnly? PlannedStartDate = null,
    DateOnly? PlannedEndDate = null,
    decimal? EstimatedHours = null,
    int SortOrder = 0);

public sealed record UpdateProjectTaskRequest(
    string? Title = null,
    Guid? ProjectServiceId = null,
    string? Description = null,
    string? Period = null,
    string? Phase = null,
    string? Stage = null,
    string? Priority = null,
    DateOnly? PlannedStartDate = null,
    DateOnly? PlannedEndDate = null,
    DateOnly? ActualStartDate = null,
    DateOnly? ActualEndDate = null,
    decimal? EstimatedHours = null,
    decimal? UtilizedHours = null,
    int? Progress = null,
    int? SortOrder = null);

public sealed record UpdateTaskStageRequest(
    string Stage);

public sealed record AutoGeneratedTasksSummaryDto(
    Guid ProjectId,
    int TasksCreated,
    IReadOnlyList<ProjectTaskDto> GeneratedTasks);
