using PMS.API.Modules.Projects.DTOs;

namespace PMS.API.Modules.Projects.Services;

public interface IProjectTaskService
{
    Task<AutoGeneratedTasksSummaryDto> GenerateMissingTasksAsync(Guid projectId, CancellationToken ct = default);

    Task<IReadOnlyList<AssignableTaskResourceDto>> GetAssignableResourcesAsync(
        Guid projectId,
        Guid taskId,
        CancellationToken ct = default);

    Task<IReadOnlyList<ProjectTaskAssignmentDto>> SynchronizeAssignmentsAsync(
        Guid projectId,
        Guid taskId,
        IReadOnlyList<Guid> employeeIds,
        CancellationToken ct = default);

    Task<IReadOnlyList<ProjectTaskAssignmentHistoryDto>> GetAssignmentHistoryAsync(
        Guid projectId,
        Guid taskId,
        CancellationToken ct = default);
}
