using PMS.API.Modules.Projects.DTOs;
using PMS.API.Shared.Common.Wrappers;

namespace PMS.API.Modules.Projects.Services;

public interface IProjectAppService
{
    Task<PagedResult<ProjectDto>> GetProjectsAsync(ProjectQueryParameters queryParams, CancellationToken ct = default);

    Task<ProjectDto?> GetProjectByIdAsync(Guid id, CancellationToken ct = default);

    Task<ProjectDto> CreateProjectAsync(CreateProjectRequest request, CancellationToken ct = default);

    Task<ProjectDto> UpdateProjectAsync(Guid id, UpdateProjectRequest request, CancellationToken ct = default);

    Task<bool> DeleteProjectAsync(Guid id, CancellationToken ct = default);

    Task<ProjectDto> UpdateStatusAsync(Guid id, string status, CancellationToken ct = default);

    Task<ProjectDto> UpdateWbsStatusAsync(Guid id, string wbsStatus, string? wbsSubStatus = null, CancellationToken ct = default);

    Task<NextProjectCodeDto> GetNextProjectCodeAsync(Guid clientId, CancellationToken ct = default);

    Task<IReadOnlyList<ProjectServiceDto>> GetProjectServicesAsync(Guid projectId, CancellationToken ct = default);

    Task<ProjectServiceDto?> GetProjectServiceByIdAsync(Guid projectId, Guid serviceId, CancellationToken ct = default);

    Task<ProjectServiceDto> AddProjectServiceAsync(Guid projectId, CreateProjectServiceRequest request, CancellationToken ct = default);

    Task<ProjectServiceDto> UpdateProjectServiceAsync(Guid projectId, Guid serviceId, UpdateProjectServiceRequest request, CancellationToken ct = default);

    Task<bool> DeleteProjectServiceAsync(Guid projectId, Guid serviceId, CancellationToken ct = default);

    Task<ProjectServiceDto> SetResourceLevelsAsync(Guid projectId, Guid serviceId, SetResourceLevelsRequest request, CancellationToken ct = default);

    Task<IReadOnlyList<ProjectTaskDto>> GetProjectTasksAsync(Guid projectId, CancellationToken ct = default);

    Task<ProjectTaskDto?> GetProjectTaskByIdAsync(Guid projectId, Guid taskId, CancellationToken ct = default);

    Task<ProjectTaskDto> CreateProjectTaskAsync(Guid projectId, CreateProjectTaskRequest request, CancellationToken ct = default);

    Task<ProjectTaskDto> UpdateProjectTaskAsync(Guid projectId, Guid taskId, UpdateProjectTaskRequest request, CancellationToken ct = default);

    Task<bool> DeleteProjectTaskAsync(Guid projectId, Guid taskId, CancellationToken ct = default);

    Task<ProjectTaskDto> UpdateTaskStageAsync(Guid projectId, Guid taskId, string stage, CancellationToken ct = default);

    Task<AutoGeneratedTasksSummaryDto> AutoGenerateTasksFromServicesAsync(Guid projectId, CancellationToken ct = default);

    Task<IReadOnlyList<ProjectTaskAssignmentDto>> GetTaskAssignmentsAsync(Guid projectId, Guid taskId, CancellationToken ct = default);

    Task<ProjectTaskAssignmentDto> AssignTaskResourceAsync(Guid projectId, Guid taskId, AssignTaskResourceRequest request, CancellationToken ct = default);

    Task<ProjectTaskAssignmentDto> UpdateTaskAssignmentAsync(Guid projectId, Guid taskId, Guid assignmentId, UpdateTaskAssignmentRequest request, CancellationToken ct = default);

    Task<bool> RemoveTaskAssignmentAsync(Guid projectId, Guid taskId, Guid assignmentId, CancellationToken ct = default);

    Task<TimerStatusDto> StartTaskTimerAsync(Guid projectId, Guid taskId, Guid assignmentId, CancellationToken ct = default);

    Task<TimerStatusDto> StopTaskTimerAsync(Guid projectId, Guid taskId, Guid assignmentId, CancellationToken ct = default);

    Task<IReadOnlyList<ProjectInvoiceDto>> GetProjectInvoicesAsync(Guid projectId, CancellationToken ct = default);

    Task<ProjectInvoiceDto?> GetProjectInvoiceByIdAsync(Guid projectId, Guid invoiceId, CancellationToken ct = default);

    Task<ProjectInvoiceDto> CreateProjectInvoiceAsync(Guid projectId, CreateProjectInvoiceRequest request, CancellationToken ct = default);

    Task<ProjectInvoiceDto> UpdateProjectInvoiceAsync(Guid projectId, Guid invoiceId, UpdateProjectInvoiceRequest request, CancellationToken ct = default);

    Task<bool> DeleteProjectInvoiceAsync(Guid projectId, Guid invoiceId, CancellationToken ct = default);

    Task<AutoGenerateInvoicesSummaryDto> AutoGenerateInvoicesAsync(Guid projectId, CancellationToken ct = default);

    Task<IReadOnlyList<ProjectDocumentDto>> GetProjectDocumentsAsync(Guid projectId, CancellationToken ct = default);

    Task<ProjectDocumentDto?> GetProjectDocumentByIdAsync(Guid projectId, Guid documentId, CancellationToken ct = default);

    Task<ProjectDocumentDto> UploadProjectDocumentAsync(Guid projectId, string? documentType, string? description, Microsoft.AspNetCore.Http.IFormFile file, CancellationToken ct = default);

    Task<(Stream Stream, string ContentType, string DownloadFileName)> DownloadProjectDocumentAsync(Guid projectId, Guid documentId, CancellationToken ct = default);

    Task<bool> DeleteProjectDocumentAsync(Guid projectId, Guid documentId, CancellationToken ct = default);

    Task<ProjectDto> RenewProjectAsync(Guid id, RenewProjectRequest request, CancellationToken ct = default);

    Task<ProjectDto> SaveWbsDraftAsync(Guid id, SaveWbsDraftRequest request, CancellationToken ct = default);

    Task<WbsPublishResultDto> PublishWbsAsync(Guid id, PublishWbsRequest? request = null, CancellationToken ct = default);
}






