using Microsoft.EntityFrameworkCore;
using PMS.API.Infrastructure.Persistence;
using PMS.API.Modules.Projects.DTOs;
using PMS.API.Modules.Projects.Models;
using PMS.API.Modules.Resources.Models;
using PMS.API.Shared.Exceptions;

namespace PMS.API.Modules.Projects.Services;

public sealed class ProjectTaskService(AppDbContext db) : IProjectTaskService
{
    public async Task<AutoGeneratedTasksSummaryDto> GenerateMissingTasksAsync(Guid projectId, CancellationToken ct = default)
    {
        var project = await db.Projects.FirstOrDefaultAsync(p => p.Id == projectId, ct)
            ?? throw new NotFoundException($"Project with ID '{projectId}' was not found.");

        var services = await db.ProjectServices
            .Where(s => s.ProjectId == projectId)
            .OrderBy(s => s.SortOrder)
            .ThenBy(s => s.CreatedAtUtc)
            .ToListAsync(ct);

        var existing = await db.ProjectTasks
            .Where(t => t.ProjectId == projectId)
            .Select(t => new { t.ProjectServiceId, t.Period, t.Phase, t.Title })
            .ToListAsync(ct);

        var known = existing
            .Select(t => LeafKey(t.ProjectServiceId, t.Period, t.Phase, t.Title))
            .ToHashSet(StringComparer.Ordinal);

        var created = new List<ProjectTask>();
        var order = existing.Count;

        await using var tx = await db.Database.BeginTransactionAsync(ct);
        try
        {
            foreach (var service in services)
            {
                var specs = TasksFromServiceModel(service.ServiceModel);
                var quarters = QuarterCount(service.Frequency);
                var qty = Math.Max(service.Qty, 1);
                var folderCount = quarters == 0 ? 1 : quarters;
                var totalLeaves = folderCount * qty * specs.Count;
                var serviceHours = ServiceHours(service);
                var hoursEach = totalLeaves > 0 ? Math.Round(serviceHours / totalLeaves, 2) : 0m;

                for (var q = quarters == 0 ? 0 : 1; q <= (quarters == 0 ? 0 : quarters); q++)
                {
                    var period = quarters == 0 ? "" : $"Quarter {q}";
                    for (var ap = 1; ap <= qty; ap++)
                    {
                        var phase = $"AP{ap}";
                        foreach (var spec in specs)
                        {
                            var title = $"Task {spec.Suffix}";
                            var key = LeafKey(service.Id, period, phase, title);
                            if (!known.Add(key)) continue;

                            order++;
                            var task = new ProjectTask
                            {
                                ProjectId = projectId,
                                ProjectServiceId = service.Id,
                                Title = title,
                                Description = spec.Label,
                                Period = period,
                                Phase = phase,
                                Stage = "Not Started",
                                Priority = "medium",
                                PlannedStartDate = service.StartDate ?? project.StartDate,
                                PlannedEndDate = service.EndDate ?? project.EndDate,
                                EstimatedHours = hoursEach,
                                UtilizedHours = 0m,
                                Progress = 0,
                                SortOrder = order * 10,
                            };
                            created.Add(task);
                        }
                    }
                }
            }

            if (created.Count > 0)
            {
                db.ProjectTasks.AddRange(created);
                await db.SaveChangesAsync(ct);
            }

            await tx.CommitAsync(ct);
        }
        catch
        {
            await tx.RollbackAsync(ct);
            throw;
        }

        var dtos = created.Select(t => new ProjectTaskDto(
            t.Id, t.ProjectId, t.ProjectServiceId, null, t.Title, t.Description, t.Period, t.Phase,
            t.Stage, t.Priority, t.PlannedStartDate, t.PlannedEndDate, t.ActualStartDate, t.ActualEndDate,
            t.EstimatedHours, t.UtilizedHours, t.Progress, t.SortOrder, t.CreatedAtUtc, t.UpdatedAtUtc,
            [])).ToList();

        return new AutoGeneratedTasksSummaryDto(projectId, created.Count, dtos);
    }

    public async Task<IReadOnlyList<AssignableTaskResourceDto>> GetAssignableResourcesAsync(
        Guid projectId,
        Guid taskId,
        CancellationToken ct = default)
    {
        await EnsureTaskAsync(projectId, taskId, ct);

        var team = await LoadTeamAsync(projectId, ct);
        var assigned = await db.ProjectTaskAssignments
            .Where(a => a.TaskId == taskId && a.IsActive)
            .Select(a => a.EmployeeId)
            .ToListAsync(ct);
        var assignedSet = assigned.ToHashSet();

        return team.Select(m => new AssignableTaskResourceDto(
            m.EmployeeId,
            m.Name,
            m.Code,
            m.Role,
            m.IsShadow ? "Shadow Team" : "Project Team",
            assignedSet.Contains(m.EmployeeId))).ToList();
    }

    public async Task<IReadOnlyList<ProjectTaskAssignmentDto>> SynchronizeAssignmentsAsync(
        Guid projectId,
        Guid taskId,
        IReadOnlyList<Guid> employeeIds,
        CancellationToken ct = default)
    {
        await EnsureTaskAsync(projectId, taskId, ct);

        var wanted = employeeIds.Distinct().ToList();
        var team = await LoadTeamAsync(projectId, ct);
        var teamIds = team.Select(m => m.EmployeeId).ToHashSet();
        var outsiders = wanted.Where(id => !teamIds.Contains(id)).ToList();
        if (outsiders.Count > 0)
        {
            throw new ConflictException("Only Project Team and Shadow Team members of this project can be assigned to a task.");
        }

        var activeEmployees = await db.Employees
            .Where(e => wanted.Contains(e.Id))
            .Select(e => new { e.Id, e.Status })
            .ToListAsync(ct);
        if (activeEmployees.Count != wanted.Count)
        {
            throw new NotFoundException("One or more employees were not found.");
        }
        if (activeEmployees.Any(e => e.Status != null && !e.Status.StartsWith("Active")))
        {
            throw new ConflictException("Inactive employees cannot be assigned to a task.");
        }

        var current = await db.ProjectTaskAssignments
            .IgnoreQueryFilters()
            .Where(a => a.TaskId == taskId)
            .ToListAsync(ct);

        var wantedSet = wanted.ToHashSet();
        var removedIds = new List<Guid>();
        foreach (var row in current.Where(a => a.DeletedAtUtc == null && a.IsActive && !wantedSet.Contains(a.EmployeeId) && teamIds.Contains(a.EmployeeId)))
        {
            removedIds.Add(row.EmployeeId);
            db.ProjectTaskAssignments.Remove(row);
        }

        var addedIds = new List<Guid>();
        foreach (var employeeId in wanted)
        {
            var existing = current.FirstOrDefault(a => a.EmployeeId == employeeId);
            if (existing is null)
            {
                db.ProjectTaskAssignments.Add(new ProjectTaskAssignment
                {
                    TaskId = taskId,
                    EmployeeId = employeeId,
                    Role = "Contributor",
                    UtilizedHours = 0m,
                    TimerAccumulatedSeconds = 0,
                    IsActive = true,
                });
                addedIds.Add(employeeId);
            }
            else if (existing.DeletedAtUtc != null || !existing.IsActive)
            {
                existing.DeletedAtUtc = null;
                existing.IsActive = true;
                existing.UpdatedAtUtc = DateTime.UtcNow;
                addedIds.Add(employeeId);
            }
        }

        await AddAssignmentHistoryAsync(taskId, addedIds, "Assign", team, ct);
        await AddAssignmentHistoryAsync(taskId, removedIds, "Unassign", team, ct);

        await db.SaveChangesAsync(ct);
        await DistributeProjectTeamHoursAsync(projectId, taskId, ct);

        var saved = await db.ProjectTaskAssignments
            .Include(a => a.Employee)
            .Where(a => a.TaskId == taskId && a.IsActive)
            .OrderBy(a => a.Employee!.FirstName)
            .ToListAsync(ct);

        return saved.Select(MapAssignment).ToList();
    }

    public async Task<IReadOnlyList<ProjectTaskAssignmentHistoryDto>> GetAssignmentHistoryAsync(
        Guid projectId,
        Guid taskId,
        CancellationToken ct = default)
    {
        await EnsureTaskAsync(projectId, taskId, ct);
        await BackfillCurrentAssignmentHistoryAsync(projectId, taskId, ct);

        var rows = await db.ProjectTaskAssignmentHistories
            .AsNoTracking()
            .Where(h => h.TaskId == taskId)
            .OrderBy(h => h.OccurredAtUtc)
            .ThenBy(h => h.CreatedAtUtc)
            .ToListAsync(ct);

        return rows.Select(h => new ProjectTaskAssignmentHistoryDto(
            h.Id,
            h.TaskId,
            h.EmployeeId,
            h.ResourceName,
            h.Action,
            h.TeamType,
            h.OccurredAtUtc)).ToList();
    }

    /// <summary>
    /// Hours shown as Utilized on a generated leaf task when no Project Team member is assigned.
    /// Completed stores the estimated hours; every other stage stores zero.
    /// </summary>
    public static void ApplyLeafUtilizedHours(ProjectTask task)
    {
        if (!IsGeneratedLeaf(task))
            return;

        var completed = task.Stage.Equals("Completed", StringComparison.OrdinalIgnoreCase);
        task.UtilizedHours = completed ? task.EstimatedHours ?? 0m : 0m;
    }

    /// <summary>
    /// Split this task's existing estimated hours across the Project Team members assigned to it.
    /// The share is stored as AllocatedHours. Utilized hours stay on the completion rule. Shadow Team assignments stay on the task and receive 0.
    /// </summary>
    public async Task DistributeProjectTeamHoursAsync(Guid projectId, Guid taskId, CancellationToken ct = default)
    {
        var task = await db.ProjectTasks.FirstAsync(t => t.ProjectId == projectId && t.Id == taskId, ct);
        if (!IsGeneratedLeaf(task))
            return;

        var assignments = await db.ProjectTaskAssignments
            .Where(a => a.TaskId == taskId && a.IsActive)
            .ToListAsync(ct);
        var projectTeamIds = await ProjectTeamIdsAsync(projectId, ct);
        ApplyProjectTeamHourSplit(task, assignments, projectTeamIds);
        await db.SaveChangesAsync(ct);
    }

    public static void ApplyProjectTeamHourSplit(
        ProjectTask task,
        IReadOnlyList<ProjectTaskAssignment> activeAssignments,
        IReadOnlySet<Guid> projectTeamEmployeeIds)
    {
        if (!IsGeneratedLeaf(task))
            return;

        var projectTeam = activeAssignments
            .Where(a => a.IsActive && a.DeletedAtUtc == null && projectTeamEmployeeIds.Contains(a.EmployeeId))
            .OrderBy(a => a.EmployeeId)
            .ToList();

        foreach (var other in activeAssignments.Where(a => a.IsActive && a.DeletedAtUtc == null && !projectTeamEmployeeIds.Contains(a.EmployeeId)))
        {
            other.AllocatedHours = 0m;
            if (!HasTimer(other))
                other.UtilizedHours = 0m;
        }

        if (projectTeam.Count == 0)
        {
            ApplyLeafUtilizedHours(task);
            return;
        }

        var shares = SplitHoursEvenly(task.EstimatedHours ?? 0m, projectTeam.Count);
        for (var i = 0; i < projectTeam.Count; i++)
        {
            projectTeam[i].AllocatedHours = shares[i];
            if (!HasTimer(projectTeam[i]))
                projectTeam[i].UtilizedHours = 0m;
        }

        ApplyLeafUtilizedHours(task);
    }

    /// <summary>
    /// Equal shares to 2 decimal places. The last share takes the remainder so the parts add up to the original hours.
    /// </summary>
    public static IReadOnlyList<decimal> SplitHoursEvenly(decimal total, int count)
    {
        if (count <= 0) return [];
        if (total < 0) total = 0m;
        if (count == 1) return [decimal.Round(total, 2, MidpointRounding.AwayFromZero)];

        var shares = new decimal[count];
        var even = decimal.Round(total / count, 2, MidpointRounding.AwayFromZero);
        var allocated = 0m;
        for (var i = 0; i < count - 1; i++)
        {
            shares[i] = even;
            allocated += even;
        }

        shares[count - 1] = decimal.Round(total - allocated, 2, MidpointRounding.AwayFromZero);
        return shares;
    }

    private static bool IsGeneratedLeaf(ProjectTask task) =>
        !string.IsNullOrEmpty(task.Title) && task.Title.StartsWith("Task ", StringComparison.Ordinal);

    private static bool HasTimer(ProjectTaskAssignment assignment) =>
        assignment.TimerAccumulatedSeconds > 0 || assignment.TimerStartedAtUtc.HasValue;

    private async Task<HashSet<Guid>> ProjectTeamIdsAsync(Guid projectId, CancellationToken ct)
    {
        var ids = await db.ProjectTeamMembers
            .Where(m => m.ProjectId == projectId && m.MemberRole == ProjectMemberRoles.ProjectTeam)
            .Select(m => m.EmployeeId)
            .ToListAsync(ct);
        return ids.ToHashSet();
    }

    private async Task BackfillCurrentAssignmentHistoryAsync(Guid projectId, Guid taskId, CancellationToken ct)
    {
        var active = await db.ProjectTaskAssignments
            .Include(a => a.Employee)
            .Where(a => a.TaskId == taskId && a.IsActive)
            .ToListAsync(ct);
        if (active.Count == 0) return;

        var alreadyLogged = await db.ProjectTaskAssignmentHistories
            .Where(h => h.TaskId == taskId)
            .Select(h => h.EmployeeId)
            .Distinct()
            .ToListAsync(ct);
        var known = alreadyLogged.ToHashSet();
        var missing = active.Where(a => !known.Contains(a.EmployeeId)).ToList();
        if (missing.Count == 0) return;

        var team = await LoadTeamAsync(projectId, ct);
        var teamById = team.ToDictionary(t => t.EmployeeId);
        foreach (var assignment in missing)
        {
            teamById.TryGetValue(assignment.EmployeeId, out var member);
            var employee = assignment.Employee;
            db.ProjectTaskAssignmentHistories.Add(new ProjectTaskAssignmentHistory
            {
                TaskId = taskId,
                EmployeeId = assignment.EmployeeId,
                Action = "Assign",
                ResourceName = employee is null ? "" : $"{employee.FirstName} {employee.LastName}".Trim(),
                TeamType = member?.IsShadow == true ? "Shadow Team" : "Project Team",
                OccurredAtUtc = assignment.CreatedAtUtc,
            });
        }

        await db.SaveChangesAsync(ct);
    }

    private async Task AddAssignmentHistoryAsync(
        Guid taskId,
        IReadOnlyList<Guid> employeeIds,
        string action,
        IReadOnlyList<TeamPerson> team,
        CancellationToken ct)
    {
        if (employeeIds.Count == 0) return;

        var people = await db.Employees
            .Where(e => employeeIds.Contains(e.Id))
            .Select(e => new { e.Id, e.FirstName, e.LastName })
            .ToListAsync(ct);
        var names = people.ToDictionary(e => e.Id, e => $"{e.FirstName} {e.LastName}".Trim());
        var teamById = team.ToDictionary(t => t.EmployeeId);
        var now = DateTime.UtcNow;

        foreach (var employeeId in employeeIds)
        {
            teamById.TryGetValue(employeeId, out var member);
            db.ProjectTaskAssignmentHistories.Add(new ProjectTaskAssignmentHistory
            {
                TaskId = taskId,
                EmployeeId = employeeId,
                Action = action,
                ResourceName = names.GetValueOrDefault(employeeId) ?? "",
                TeamType = member?.IsShadow == true ? "Shadow Team" : "Project Team",
                OccurredAtUtc = now,
            });
        }
    }

    internal static async Task EnsureOnProjectTeamAsync(AppDbContext db, Guid projectId, Guid employeeId, CancellationToken ct)
    {
        var onTeam = await db.ProjectTeamMembers
            .AnyAsync(m => m.ProjectId == projectId && m.EmployeeId == employeeId &&
                           (m.MemberRole == ProjectMemberRoles.ProjectTeam || m.MemberRole == ProjectMemberRoles.ShadowTeam), ct);
        if (!onTeam)
        {
            throw new ConflictException("Only Project Team and Shadow Team members of this project can be assigned to a task.");
        }
    }

    private async Task EnsureTaskAsync(Guid projectId, Guid taskId, CancellationToken ct)
    {
        var exists = await db.ProjectTasks.AnyAsync(t => t.ProjectId == projectId && t.Id == taskId, ct);
        if (!exists)
            throw new NotFoundException($"Project Task with ID '{taskId}' was not found in this project.");
    }

    private async Task<List<TeamPerson>> LoadTeamAsync(Guid projectId, CancellationToken ct)
    {
        var rows = await db.ProjectTeamMembers
            .AsNoTracking()
            .Include(m => m.Employee)!.ThenInclude(e => e.JobRole)
            .Where(m => m.ProjectId == projectId && m.Employee != null &&
                        (m.MemberRole == ProjectMemberRoles.ProjectTeam || m.MemberRole == ProjectMemberRoles.ShadowTeam))
            .ToListAsync(ct);

        return rows
            .GroupBy(m => m.EmployeeId)
            .Select(g =>
            {
                var pick = g.FirstOrDefault(m => !m.IsShadowTeam) ?? g.First();
                var emp = pick.Employee!;
                return new TeamPerson(
                    pick.EmployeeId,
                    $"{emp.FirstName} {emp.LastName}".Trim(),
                    emp.EmployeeCode,
                    emp.JobRole?.Name ?? emp.Role,
                    pick.IsShadowTeam);
            })
            .OrderBy(p => p.IsShadow)
            .ThenBy(p => p.Name)
            .ToList();
    }

    private static string LeafKey(Guid? serviceId, string? period, string? phase, string title) =>
        $"{serviceId}|{period ?? ""}|{phase ?? ""}|{title}";

    private static int QuarterCount(string? frequency)
    {
        var freq = (frequency ?? "Once").ToLowerInvariant();
        if (freq.Contains("half")) return 2;
        if (freq.Contains("year")) return 4;
        return 0;
    }

    private static decimal ServiceHours(ProjectServiceEntity service)
    {
        if (service.TotalHours is > 0) return service.TotalHours.Value;
        if (service.TotalDays is > 0) return service.TotalDays.Value * 8m;
        if (service.DurationDays is > 0) return service.DurationDays.Value * 8m;
        if (service.DurationHours is > 0) return service.DurationHours.Value;
        return 0m;
    }

    private static List<(string Suffix, string Label)> TasksFromServiceModel(string? model)
    {
        var norm = (model ?? "").Trim().ToUpperInvariant();
        if (norm is "NA" or "N/A")
            return [("01", "NA")];
        if (norm.Contains("INITIAL + 1"))
            return [("01", "Initial Test"), ("02", "Retest 1")];
        if (norm.Contains("INITIAL + 2"))
            return [("01", "Initial Test"), ("02", "Retest 1"), ("03", "Retest 2")];
        if (norm.Contains("INITIAL + 3"))
            return [("01", "Initial Test"), ("02", "Retest 1"), ("03", "Retest 2"), ("04", "Retest 3")];
        return [("01", "Initial Test")];
    }

    private static ProjectTaskAssignmentDto MapAssignment(ProjectTaskAssignment a)
    {
        var emp = a.Employee;
        return new ProjectTaskAssignmentDto(
            a.Id,
            a.TaskId,
            a.EmployeeId,
            emp is null ? "" : $"{emp.FirstName} {emp.LastName}".Trim(),
            emp?.EmployeeCode ?? "",
            emp?.WorkEmail,
            a.Role,
            a.AllocatedHours,
            a.UtilizedHours,
            a.TimerStartedAtUtc,
            a.TimerAccumulatedSeconds,
            a.IsActive,
            a.TimerStartedAtUtc.HasValue,
            a.CreatedAtUtc,
            a.UpdatedAtUtc);
    }

    private sealed record TeamPerson(Guid EmployeeId, string Name, string Code, string? Role, bool IsShadow);
}
