/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WbsPrerequisiteNewRouteImport } from './routes/wbs-prerequisite-new'
import { Route as WbsAllocationRouteImport } from './routes/wbs-allocation'
import { Route as TimesheetRouteImport } from './routes/timesheet'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MyTeamRouteImport } from './routes/my-team'
import { Route as MyOrgRouteImport } from './routes/my-org'
import { Route as HealthInterviewSchedulingRouteImport } from './routes/health-interview-scheduling'
import { Route as HealthAdditionalRequirementsRouteImport } from './routes/health-additional-requirements'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DhSettingsSecurityRolesRouteImport } from './routes/dh-settings-security-roles'
import { Route as DhSettingsRouteImport } from './routes/dh-settings'
import { Route as DhResourcePoolRouteImport } from './routes/dh-resource-pool'
import { Route as DhReportsRouteImport } from './routes/dh-reports'
import { Route as DhOrgTreeRouteImport } from './routes/dh-org-tree'
import { Route as DhExitSummaryRouteImport } from './routes/dh-exit-summary'
import { Route as DhEmployeeDirectoryRouteImport } from './routes/dh-employee-directory'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as ActionCentreRouteImport } from './routes/action-centre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as DhEmployeeDirectoryIndexRouteImport } from './routes/dh-employee-directory.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DhEmployeeDirectoryIdRouteImport } from './routes/dh-employee-directory.$id'
import { Route as CustomersClientIdRouteImport } from './routes/customers.$clientId'
import { Route as CustomerDetailClientIdRouteImport } from './routes/customer-detail.$clientId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const WbsPrerequisiteNewRoute = WbsPrerequisiteNewRouteImport.update({
  id: '/wbs-prerequisite-new',
  path: '/wbs-prerequisite-new',
  getParentRoute: () => rootRouteImport,
} as any)
const WbsAllocationRoute = WbsAllocationRouteImport.update({
  id: '/wbs-allocation',
  path: '/wbs-allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetRoute = TimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamRoute = MyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrgRoute = MyOrgRouteImport.update({
  id: '/my-org',
  path: '/my-org',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthInterviewSchedulingRoute =
  HealthInterviewSchedulingRouteImport.update({
    id: '/health-interview-scheduling',
    path: '/health-interview-scheduling',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthAdditionalRequirementsRoute =
  HealthAdditionalRequirementsRouteImport.update({
    id: '/health-additional-requirements',
    path: '/health-additional-requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DhSettingsSecurityRolesRoute = DhSettingsSecurityRolesRouteImport.update({
  id: '/dh-settings-security-roles',
  path: '/dh-settings-security-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DhSettingsRoute = DhSettingsRouteImport.update({
  id: '/dh-settings',
  path: '/dh-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DhResourcePoolRoute = DhResourcePoolRouteImport.update({
  id: '/dh-resource-pool',
  path: '/dh-resource-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const DhReportsRoute = DhReportsRouteImport.update({
  id: '/dh-reports',
  path: '/dh-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DhOrgTreeRoute = DhOrgTreeRouteImport.update({
  id: '/dh-org-tree',
  path: '/dh-org-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const DhExitSummaryRoute = DhExitSummaryRouteImport.update({
  id: '/dh-exit-summary',
  path: '/dh-exit-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DhEmployeeDirectoryRoute = DhEmployeeDirectoryRouteImport.update({
  id: '/dh-employee-directory',
  path: '/dh-employee-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionCentreRoute = ActionCentreRouteImport.update({
  id: '/action-centre',
  path: '/action-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DhEmployeeDirectoryIndexRoute =
  DhEmployeeDirectoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DhEmployeeDirectoryRoute,
  } as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DhEmployeeDirectoryIdRoute = DhEmployeeDirectoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DhEmployeeDirectoryRoute,
} as any)
const CustomersClientIdRoute = CustomersClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomerDetailClientIdRoute = CustomerDetailClientIdRouteImport.update({
  id: '/customer-detail/$clientId',
  path: '/customer-detail/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-centre': typeof ActionCentreRoute
  '/allocation': typeof AllocationRoute
  '/approvals': typeof ApprovalsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dh-employee-directory': typeof DhEmployeeDirectoryRouteWithChildren
  '/dh-exit-summary': typeof DhExitSummaryRoute
  '/dh-org-tree': typeof DhOrgTreeRoute
  '/dh-reports': typeof DhReportsRoute
  '/dh-resource-pool': typeof DhResourcePoolRoute
  '/dh-settings': typeof DhSettingsRoute
  '/dh-settings-security-roles': typeof DhSettingsSecurityRolesRoute
  '/health': typeof HealthRoute
  '/health-additional-requirements': typeof HealthAdditionalRequirementsRoute
  '/health-interview-scheduling': typeof HealthInterviewSchedulingRoute
  '/my-org': typeof MyOrgRoute
  '/my-team': typeof MyTeamRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/timesheet': typeof TimesheetRoute
  '/wbs-allocation': typeof WbsAllocationRoute
  '/wbs-prerequisite-new': typeof WbsPrerequisiteNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/customer-detail/$clientId': typeof CustomerDetailClientIdRoute
  '/customers/$clientId': typeof CustomersClientIdRoute
  '/dh-employee-directory/$id': typeof DhEmployeeDirectoryIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/dh-employee-directory/': typeof DhEmployeeDirectoryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-centre': typeof ActionCentreRoute
  '/allocation': typeof AllocationRoute
  '/approvals': typeof ApprovalsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dh-exit-summary': typeof DhExitSummaryRoute
  '/dh-org-tree': typeof DhOrgTreeRoute
  '/dh-reports': typeof DhReportsRoute
  '/dh-resource-pool': typeof DhResourcePoolRoute
  '/dh-settings': typeof DhSettingsRoute
  '/dh-settings-security-roles': typeof DhSettingsSecurityRolesRoute
  '/health': typeof HealthRoute
  '/health-additional-requirements': typeof HealthAdditionalRequirementsRoute
  '/health-interview-scheduling': typeof HealthInterviewSchedulingRoute
  '/my-org': typeof MyOrgRoute
  '/my-team': typeof MyTeamRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/timesheet': typeof TimesheetRoute
  '/wbs-allocation': typeof WbsAllocationRoute
  '/wbs-prerequisite-new': typeof WbsPrerequisiteNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/customer-detail/$clientId': typeof CustomerDetailClientIdRoute
  '/customers/$clientId': typeof CustomersClientIdRoute
  '/dh-employee-directory/$id': typeof DhEmployeeDirectoryIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/dh-employee-directory': typeof DhEmployeeDirectoryIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-centre': typeof ActionCentreRoute
  '/allocation': typeof AllocationRoute
  '/approvals': typeof ApprovalsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dh-employee-directory': typeof DhEmployeeDirectoryRouteWithChildren
  '/dh-exit-summary': typeof DhExitSummaryRoute
  '/dh-org-tree': typeof DhOrgTreeRoute
  '/dh-reports': typeof DhReportsRoute
  '/dh-resource-pool': typeof DhResourcePoolRoute
  '/dh-settings': typeof DhSettingsRoute
  '/dh-settings-security-roles': typeof DhSettingsSecurityRolesRoute
  '/health': typeof HealthRoute
  '/health-additional-requirements': typeof HealthAdditionalRequirementsRoute
  '/health-interview-scheduling': typeof HealthInterviewSchedulingRoute
  '/my-org': typeof MyOrgRoute
  '/my-team': typeof MyTeamRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/timesheet': typeof TimesheetRoute
  '/wbs-allocation': typeof WbsAllocationRoute
  '/wbs-prerequisite-new': typeof WbsPrerequisiteNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/customer-detail/$clientId': typeof CustomerDetailClientIdRoute
  '/customers/$clientId': typeof CustomersClientIdRoute
  '/dh-employee-directory/$id': typeof DhEmployeeDirectoryIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/dh-employee-directory/': typeof DhEmployeeDirectoryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-centre'
    | '/allocation'
    | '/approvals'
    | '/customers'
    | '/dh-employee-directory'
    | '/dh-exit-summary'
    | '/dh-org-tree'
    | '/dh-reports'
    | '/dh-resource-pool'
    | '/dh-settings'
    | '/dh-settings-security-roles'
    | '/health'
    | '/health-additional-requirements'
    | '/health-interview-scheduling'
    | '/my-org'
    | '/my-team'
    | '/portfolio'
    | '/reports'
    | '/resources'
    | '/timesheet'
    | '/wbs-allocation'
    | '/wbs-prerequisite-new'
    | '/clients/$clientId'
    | '/customer-detail/$clientId'
    | '/customers/$clientId'
    | '/dh-employee-directory/$id'
    | '/projects/$projectId'
    | '/projects/new'
    | '/clients/'
    | '/dh-employee-directory/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-centre'
    | '/allocation'
    | '/approvals'
    | '/customers'
    | '/dh-exit-summary'
    | '/dh-org-tree'
    | '/dh-reports'
    | '/dh-resource-pool'
    | '/dh-settings'
    | '/dh-settings-security-roles'
    | '/health'
    | '/health-additional-requirements'
    | '/health-interview-scheduling'
    | '/my-org'
    | '/my-team'
    | '/portfolio'
    | '/reports'
    | '/resources'
    | '/timesheet'
    | '/wbs-allocation'
    | '/wbs-prerequisite-new'
    | '/clients/$clientId'
    | '/customer-detail/$clientId'
    | '/customers/$clientId'
    | '/dh-employee-directory/$id'
    | '/projects/$projectId'
    | '/projects/new'
    | '/clients'
    | '/dh-employee-directory'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/action-centre'
    | '/allocation'
    | '/approvals'
    | '/customers'
    | '/dh-employee-directory'
    | '/dh-exit-summary'
    | '/dh-org-tree'
    | '/dh-reports'
    | '/dh-resource-pool'
    | '/dh-settings'
    | '/dh-settings-security-roles'
    | '/health'
    | '/health-additional-requirements'
    | '/health-interview-scheduling'
    | '/my-org'
    | '/my-team'
    | '/portfolio'
    | '/reports'
    | '/resources'
    | '/timesheet'
    | '/wbs-allocation'
    | '/wbs-prerequisite-new'
    | '/clients/$clientId'
    | '/customer-detail/$clientId'
    | '/customers/$clientId'
    | '/dh-employee-directory/$id'
    | '/projects/$projectId'
    | '/projects/new'
    | '/clients/'
    | '/dh-employee-directory/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionCentreRoute: typeof ActionCentreRoute
  AllocationRoute: typeof AllocationRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DhEmployeeDirectoryRoute: typeof DhEmployeeDirectoryRouteWithChildren
  DhExitSummaryRoute: typeof DhExitSummaryRoute
  DhOrgTreeRoute: typeof DhOrgTreeRoute
  DhReportsRoute: typeof DhReportsRoute
  DhResourcePoolRoute: typeof DhResourcePoolRoute
  DhSettingsRoute: typeof DhSettingsRoute
  DhSettingsSecurityRolesRoute: typeof DhSettingsSecurityRolesRoute
  HealthRoute: typeof HealthRoute
  HealthAdditionalRequirementsRoute: typeof HealthAdditionalRequirementsRoute
  HealthInterviewSchedulingRoute: typeof HealthInterviewSchedulingRoute
  MyOrgRoute: typeof MyOrgRoute
  MyTeamRoute: typeof MyTeamRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  TimesheetRoute: typeof TimesheetRoute
  WbsAllocationRoute: typeof WbsAllocationRoute
  WbsPrerequisiteNewRoute: typeof WbsPrerequisiteNewRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  CustomerDetailClientIdRoute: typeof CustomerDetailClientIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wbs-prerequisite-new': {
      id: '/wbs-prerequisite-new'
      path: '/wbs-prerequisite-new'
      fullPath: '/wbs-prerequisite-new'
      preLoaderRoute: typeof WbsPrerequisiteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wbs-allocation': {
      id: '/wbs-allocation'
      path: '/wbs-allocation'
      fullPath: '/wbs-allocation'
      preLoaderRoute: typeof WbsAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheet': {
      id: '/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof TimesheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-team': {
      id: '/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof MyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-org': {
      id: '/my-org'
      path: '/my-org'
      fullPath: '/my-org'
      preLoaderRoute: typeof MyOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-interview-scheduling': {
      id: '/health-interview-scheduling'
      path: '/health-interview-scheduling'
      fullPath: '/health-interview-scheduling'
      preLoaderRoute: typeof HealthInterviewSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-additional-requirements': {
      id: '/health-additional-requirements'
      path: '/health-additional-requirements'
      fullPath: '/health-additional-requirements'
      preLoaderRoute: typeof HealthAdditionalRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-settings-security-roles': {
      id: '/dh-settings-security-roles'
      path: '/dh-settings-security-roles'
      fullPath: '/dh-settings-security-roles'
      preLoaderRoute: typeof DhSettingsSecurityRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-settings': {
      id: '/dh-settings'
      path: '/dh-settings'
      fullPath: '/dh-settings'
      preLoaderRoute: typeof DhSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-resource-pool': {
      id: '/dh-resource-pool'
      path: '/dh-resource-pool'
      fullPath: '/dh-resource-pool'
      preLoaderRoute: typeof DhResourcePoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-reports': {
      id: '/dh-reports'
      path: '/dh-reports'
      fullPath: '/dh-reports'
      preLoaderRoute: typeof DhReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-org-tree': {
      id: '/dh-org-tree'
      path: '/dh-org-tree'
      fullPath: '/dh-org-tree'
      preLoaderRoute: typeof DhOrgTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-exit-summary': {
      id: '/dh-exit-summary'
      path: '/dh-exit-summary'
      fullPath: '/dh-exit-summary'
      preLoaderRoute: typeof DhExitSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-employee-directory': {
      id: '/dh-employee-directory'
      path: '/dh-employee-directory'
      fullPath: '/dh-employee-directory'
      preLoaderRoute: typeof DhEmployeeDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-centre': {
      id: '/action-centre'
      path: '/action-centre'
      fullPath: '/action-centre'
      preLoaderRoute: typeof ActionCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-employee-directory/': {
      id: '/dh-employee-directory/'
      path: '/'
      fullPath: '/dh-employee-directory/'
      preLoaderRoute: typeof DhEmployeeDirectoryIndexRouteImport
      parentRoute: typeof DhEmployeeDirectoryRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dh-employee-directory/$id': {
      id: '/dh-employee-directory/$id'
      path: '/$id'
      fullPath: '/dh-employee-directory/$id'
      preLoaderRoute: typeof DhEmployeeDirectoryIdRouteImport
      parentRoute: typeof DhEmployeeDirectoryRoute
    }
    '/customers/$clientId': {
      id: '/customers/$clientId'
      path: '/$clientId'
      fullPath: '/customers/$clientId'
      preLoaderRoute: typeof CustomersClientIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customer-detail/$clientId': {
      id: '/customer-detail/$clientId'
      path: '/customer-detail/$clientId'
      fullPath: '/customer-detail/$clientId'
      preLoaderRoute: typeof CustomerDetailClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersClientIdRoute: typeof CustomersClientIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersClientIdRoute: CustomersClientIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface DhEmployeeDirectoryRouteChildren {
  DhEmployeeDirectoryIdRoute: typeof DhEmployeeDirectoryIdRoute
  DhEmployeeDirectoryIndexRoute: typeof DhEmployeeDirectoryIndexRoute
}

const DhEmployeeDirectoryRouteChildren: DhEmployeeDirectoryRouteChildren = {
  DhEmployeeDirectoryIdRoute: DhEmployeeDirectoryIdRoute,
  DhEmployeeDirectoryIndexRoute: DhEmployeeDirectoryIndexRoute,
}

const DhEmployeeDirectoryRouteWithChildren =
  DhEmployeeDirectoryRoute._addFileChildren(DhEmployeeDirectoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionCentreRoute: ActionCentreRoute,
  AllocationRoute: AllocationRoute,
  ApprovalsRoute: ApprovalsRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DhEmployeeDirectoryRoute: DhEmployeeDirectoryRouteWithChildren,
  DhExitSummaryRoute: DhExitSummaryRoute,
  DhOrgTreeRoute: DhOrgTreeRoute,
  DhReportsRoute: DhReportsRoute,
  DhResourcePoolRoute: DhResourcePoolRoute,
  DhSettingsRoute: DhSettingsRoute,
  DhSettingsSecurityRolesRoute: DhSettingsSecurityRolesRoute,
  HealthRoute: HealthRoute,
  HealthAdditionalRequirementsRoute: HealthAdditionalRequirementsRoute,
  HealthInterviewSchedulingRoute: HealthInterviewSchedulingRoute,
  MyOrgRoute: MyOrgRoute,
  MyTeamRoute: MyTeamRoute,
  PortfolioRoute: PortfolioRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  TimesheetRoute: TimesheetRoute,
  WbsAllocationRoute: WbsAllocationRoute,
  WbsPrerequisiteNewRoute: WbsPrerequisiteNewRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  CustomerDetailClientIdRoute: CustomerDetailClientIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
